In [ ]:
# import
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time
import random
import os
import json
from datetime import datetime, timedelta
from dateutil import parser

In [2]:
# 설정
HEADERS = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)"}

MAX_PAGES = 5
BASE_DIR = "inven_out"

# 실제 게시판 URL
LOSTARK_MOBILE_URL = "https://www.inven.co.kr/board/lostarkmobile/6389"
AION2_URL = "https://www.inven.co.kr/board/aion2/6388?my=chuchu"

# 아이온2 출시 기준 2주
AION2_RELEASE_DATE = datetime(2025, 11, 19)
AION2_START = AION2_RELEASE_DATE - timedelta(days=14)
AION2_END = AION2_RELEASE_DATE + timedelta(days=14)

def sleep():
    time.sleep(random.uniform(1.0, 2.0))

def ensure_dir(path):
    os.makedirs(path, exist_ok=True)

def load_state(path):
    if os.path.exists(path):
        with open(path, "r", encoding="utf-8") as f:
            return json.load(f)
    return {"done_urls": [], "data": []}

def save_state(path, state):
    with open(path, "w", encoding="utf-8") as f:
        json.dump(state, f, ensure_ascii=False, indent=2)

In [3]:
# 링크 수집
def get_post_links(base_url, page):
    url = f"{base_url}?p={page}"
    res = requests.get(url, headers=HEADERS)
    soup = BeautifulSoup(res.text, "html.parser")

    links = []
    rows = soup.select("table tbody tr")
    for row in rows:
        a_tag = row.select_one("td.tit a")
        if not a_tag:
            continue
        title = a_tag.text.strip()
        link = a_tag.get("href")
        links.append((title, link))
    return links

# 상세 수집
def get_post_detail(title, url):
    res = requests.get(url, headers=HEADERS)
    soup = BeautifulSoup(res.text, "html.parser")

    content_tag = soup.select_one(".contentBody")
    content = content_tag.text.strip() if content_tag else ""

    created_at = ""
    date_tag = soup.select_one(".articleDate")
    if date_tag:
        created_at = date_tag.text.strip()

    views = 0
    view_tag = soup.select_one(".articleHit")
    if view_tag:
        try:
            views = int(view_tag.text.replace(",", "").strip())
        except:
            pass

    likes = 0
    like_tag = soup.select_one("div.recommend span.num")
    if like_tag:
        try:
            likes = int(like_tag.text.strip())
        except:
            pass

    comments = []
    comment_tags = soup.select(".cmtContent")
    for c in comment_tags:
        text = c.text.strip()
        if text:
            comments.append(text)

    return {
        "title": title,
        "content": content,
        "comments": comments,
        "url": url,
        "created_at": created_at,
        "views": views,
        "likes": likes,
        "comment_count": len(comments)
    }

# 크롤링 (중간 저장 + 진행률 표시)
def crawl_inven(base_url, game_type, filter_dates=None):
    game_dir = os.path.join(BASE_DIR, game_type)
    ensure_dir(game_dir)

    state_path = os.path.join(game_dir, "state.json")
    state = load_state(state_path)

    done_urls = set(state["done_urls"])
    data = state["data"]

    all_links = []
    for page in range(1, MAX_PAGES + 1):
        print(f"[{game_type}] page {page}/{MAX_PAGES}")
        links = get_post_links(base_url, page)
        all_links.extend(links)
        sleep()

    total_posts = len(all_links)
    print(f"[{game_type}] total {total_posts} posts")

    for idx, (title, link) in enumerate(all_links, 1):
        if link in done_urls:
            continue

        try:
            post_data = get_post_detail(title, link)

            # 아이온2 날짜 필터
            if filter_dates:
                try:
                    post_dt = datetime.strptime(post_data['created_at'], "%Y-%m-%d %H:%M")
                    if post_dt < filter_dates[0] or post_dt > filter_dates[1]:
                        continue
                except:
                    pass

            # 진행률 표시
            percent = round(idx / total_posts * 100, 1)
            print(f"[posts] {idx}/{total_posts} ({percent}%)")
            print(f"[comments] {link.split('/')[-1]} -> {post_data['comment_count']} comments")

            data.append(post_data)
            done_urls.add(link)

            # 중간저장
            save_state(state_path, {"done_urls": list(done_urls), "data": data})
            sleep()
        except Exception as e:
            print("error:", e)

    return data

# CSV 저장
def save_to_csv(data, game_type):
    game_dir = os.path.join(BASE_DIR, game_type)
    ensure_dir(game_dir)

    today = datetime.now().strftime("%Y%m%d")
    filename = os.path.join(game_dir, f"{game_type}_{today}.csv")

    rows = []
    for post in data:
        if post["comments"]:
            for c in post["comments"]:
                rows.append({
                    "title": post["title"],
                    "content": post["content"],
                    "comment": c,
                    "url": post["url"],
                    "created_at": post["created_at"],
                    "views": post["views"],
                    "likes": post["likes"],
                    "comment_count": post["comment_count"]
                })
        else:
            rows.append({
                "title": post["title"],
                "content": post["content"],
                "comment": "",
                "url": post["url"],
                "created_at": post["created_at"],
                "views": post["views"],
                "likes": post["likes"],
                "comment_count": post["comment_count"]
            })

    df = pd.DataFrame(rows)
    df.to_csv(filename, index=False, encoding="utf-8-sig")
    print(f"Saved {filename}")

In [18]:
# 실행

# 로스트아크 모바일
lostark_data = crawl_inven(LOSTARK_MOBILE_URL, "lostark_mobile")
save_to_csv(lostark_data, "lostark_mobile")

# 아이온2
aion2_data = crawl_inven(
    AION2_URL,
    "aion2",
    filter_dates=(AION2_START, AION2_END)
)
save_to_csv(aion2_data, "aion2")

print("Done crawling")

[lostark_mobile] page 1/5
[lostark_mobile] page 2/5
[lostark_mobile] page 3/5
[lostark_mobile] page 4/5
[lostark_mobile] page 5/5
[lostark_mobile] total 226 posts
[posts] 1/226 (0.4%)
[comments] 1176 -> 0 comments
[posts] 2/226 (0.9%)
[comments] 1229 -> 0 comments
[posts] 3/226 (1.3%)
[comments] 1197 -> 0 comments
[posts] 4/226 (1.8%)
[comments] 1193 -> 0 comments
[posts] 5/226 (2.2%)
[comments] 1191 -> 0 comments
[posts] 6/226 (2.7%)
[comments] 1190 -> 0 comments
[posts] 7/226 (3.1%)
[comments] 1189 -> 0 comments
[posts] 8/226 (3.5%)
[comments] 1188 -> 0 comments
[posts] 9/226 (4.0%)
[comments] 1187 -> 0 comments
[posts] 10/226 (4.4%)
[comments] 1186 -> 0 comments
[posts] 11/226 (4.9%)
[comments] 1185 -> 0 comments
[posts] 12/226 (5.3%)
[comments] 1184 -> 0 comments
[posts] 13/226 (5.8%)
[comments] 1181 -> 0 comments
[posts] 14/226 (6.2%)
[comments] 1180 -> 0 comments
[posts] 15/226 (6.6%)
[comments] 1179 -> 0 comments
[posts] 16/226 (7.1%)
[comments] 1178 -> 0 comments
[posts] 17/226 (7.5%)
[comments] 1177 -> 0 comments
[posts] 19/226 (8.4%)
[comments] 1175 -> 0 comments
[posts] 20/226 (8.8%)
[comments] 1174 -> 0 comments
[posts] 21/226 (9.3%)
[comments] 1173 -> 0 comments
[posts] 22/226 (9.7%)
[comments] 1172 -> 0 comments
[posts] 23/226 (10.2%)
[comments] 1171 -> 0 comments
[posts] 24/226 (10.6%)
[comments] 1170 -> 0 comments
[posts] 25/226 (11.1%)
[comments] 1169 -> 0 comments
[posts] 26/226 (11.5%)
[comments] 1168 -> 0 comments
[posts] 27/226 (11.9%)
[comments] 1167 -> 0 comments
[posts] 28/226 (12.4%)
[comments] 1166 -> 0 comments
[posts] 29/226 (12.8%)
[comments] 1165 -> 0 comments
[posts] 30/226 (13.3%)
[comments] 1164 -> 0 comments
[posts] 31/226 (13.7%)
[comments] 1163 -> 0 comments
[posts] 32/226 (14.2%)
[comments] 1162 -> 0 comments
[posts] 33/226 (14.6%)
[comments] 1161 -> 0 comments
[posts] 34/226 (15.0%)
[comments] 1160 -> 0 comments
[posts] 35/226 (15.5%)
[comments] 1159 -> 0 comments
[posts] 36/226 (15.9%)
[comments] 1158 -> 0 comments
[posts] 37/226 (16.4%)
[comments] 1157 -> 0 comments
[posts] 38/226 (16.8%)
[comments] 1156 -> 0 comments
[posts] 39/226 (17.3%)
[comments] 1155 -> 0 comments
[posts] 40/226 (17.7%)
[comments] 1154 -> 0 comments
[posts] 41/226 (18.1%)
[comments] 1153 -> 0 comments
[posts] 42/226 (18.6%)
[comments] 1152 -> 0 comments
[posts] 43/226 (19.0%)
[comments] 1151 -> 0 comments
[posts] 44/226 (19.5%)
[comments] 1150 -> 0 comments
[posts] 45/226 (19.9%)
[comments] 1149 -> 0 comments
[posts] 46/226 (20.4%)
[comments] 1148 -> 0 comments
[posts] 47/226 (20.8%)
[comments] 1147?p=2 -> 0 comments
[posts] 48/226 (21.2%)
[comments] 1146?p=2 -> 0 comments
[posts] 49/226 (21.7%)
[comments] 1145?p=2 -> 0 comments
[posts] 50/226 (22.1%)
[comments] 1144?p=2 -> 0 comments
[posts] 51/226 (22.6%)
[comments] 1143?p=2 -> 0 comments
[posts] 52/226 (23.0%)
[comments] 1142?p=2 -> 0 comments
[posts] 53/226 (23.5%)
[comments] 1141?p=2 -> 0 comments
[posts] 54/226 (23.9%)
[comments] 1140?p=2 -> 0 comments
[posts] 55/226 (24.3%)
[comments] 1139?p=2 -> 0 comments
[posts] 56/226 (24.8%)
[comments] 1138?p=2 -> 0 comments
[posts] 57/226 (25.2%)
[comments] 1137?p=2 -> 0 comments
[posts] 58/226 (25.7%)
[comments] 1136?p=2 -> 0 comments
[posts] 59/226 (26.1%)
[comments] 1135?p=2 -> 0 comments
[posts] 60/226 (26.5%)
[comments] 1134?p=2 -> 0 comments
[posts] 61/226 (27.0%)
[comments] 1133?p=2 -> 0 comments
[posts] 62/226 (27.4%)
[comments] 1132?p=2 -> 0 comments
[posts] 63/226 (27.9%)
[comments] 1131?p=2 -> 0 comments
[posts] 64/226 (28.3%)
[comments] 1130?p=2 -> 0 comments
[posts] 65/226 (28.8%)
[comments] 1129?p=2 -> 0 comments
[posts] 66/226 (29.2%)
[comments] 1128?p=2 -> 0 comments
[posts] 67/226 (29.6%)
[comments] 1127?p=2 -> 0 comments
[posts] 68/226 (30.1%)
[comments] 1126?p=2 -> 0 comments
[posts] 69/226 (30.5%)
[comments] 1125?p=2 -> 0 comments
[posts] 70/226 (31.0%)
[comments] 1124?p=2 -> 0 comments
[posts] 71/226 (31.4%)
[comments] 1123?p=2 -> 0 comments
[posts] 72/226 (31.9%)
[comments] 1122?p=2 -> 0 comments
[posts] 73/226 (32.3%)
[comments] 1121?p=2 -> 0 comments
[posts] 74/226 (32.7%)
[comments] 1120?p=2 -> 0 comments
[posts] 75/226 (33.2%)
[comments] 1119?p=2 -> 0 comments
[posts] 76/226 (33.6%)
[comments] 1118?p=2 -> 0 comments
[posts] 77/226 (34.1%)
[comments] 1117?p=2 -> 0 comments
[posts] 78/226 (34.5%)
[comments] 1116?p=2 -> 0 comments
[posts] 79/226 (35.0%)
[comments] 1115?p=2 -> 0 comments
[posts] 80/226 (35.4%)
[comments] 1114?p=2 -> 0 comments
[posts] 81/226 (35.8%)
[comments] 1113?p=2 -> 0 comments
[posts] 82/226 (36.3%)
[comments] 1112?p=2 -> 0 comments
[posts] 83/226 (36.7%)
[comments] 1111?p=2 -> 0 comments
[posts] 84/226 (37.2%)
[comments] 1110?p=2 -> 0 comments
[posts] 85/226 (37.6%)
[comments] 1109?p=2 -> 0 comments
[posts] 86/226 (38.1%)
[comments] 1108?p=2 -> 0 comments
[posts] 87/226 (38.5%)
[comments] 1107?p=2 -> 0 comments
[posts] 88/226 (38.9%)
[comments] 1106?p=2 -> 0 comments
[posts] 89/226 (39.4%)
[comments] 1105?p=2 -> 0 comments
[posts] 90/226 (39.8%)
[comments] 1104?p=2 -> 0 comments
[posts] 91/226 (40.3%)
[comments] 1103?p=2 -> 0 comments
[posts] 92/226 (40.7%)
[comments] 1102?p=3 -> 0 comments
[posts] 93/226 (41.2%)
[comments] 1101?p=3 -> 0 comments
[posts] 94/226 (41.6%)
[comments] 1100?p=3 -> 0 comments
[posts] 95/226 (42.0%)
[comments] 1099?p=3 -> 0 comments
[posts] 96/226 (42.5%)
[comments] 1098?p=3 -> 0 comments
[posts] 97/226 (42.9%)
[comments] 1097?p=3 -> 0 comments
[posts] 98/226 (43.4%)
[comments] 1096?p=3 -> 0 comments
[posts] 99/226 (43.8%)
[comments] 1095?p=3 -> 0 comments
[posts] 100/226 (44.2%)
[comments] 1094?p=3 -> 0 comments
[posts] 101/226 (44.7%)
[comments] 1093?p=3 -> 0 comments
[posts] 102/226 (45.1%)
[comments] 1092?p=3 -> 0 comments
[posts] 103/226 (45.6%)
[comments] 1091?p=3 -> 0 comments
[posts] 104/226 (46.0%)
[comments] 1090?p=3 -> 0 comments
[posts] 105/226 (46.5%)
[comments] 1089?p=3 -> 0 comments
[posts] 106/226 (46.9%)
[comments] 1088?p=3 -> 0 comments
[posts] 107/226 (47.3%)
[comments] 1087?p=3 -> 0 comments
[posts] 108/226 (47.8%)
[comments] 1086?p=3 -> 0 comments
[posts] 109/226 (48.2%)
[comments] 1085?p=3 -> 0 comments
[posts] 110/226 (48.7%)
[comments] 1084?p=3 -> 0 comments
[posts] 111/226 (49.1%)
[comments] 1082?p=3 -> 0 comments
[posts] 112/226 (49.6%)
[comments] 1081?p=3 -> 0 comments
[posts] 113/226 (50.0%)
[comments] 1080?p=3 -> 0 comments
[posts] 114/226 (50.4%)
[comments] 1079?p=3 -> 0 comments
[posts] 115/226 (50.9%)
[comments] 1078?p=3 -> 0 comments
[posts] 116/226 (51.3%)
[comments] 1076?p=3 -> 0 comments
[posts] 117/226 (51.8%)
[comments] 1075?p=3 -> 0 comments
[posts] 118/226 (52.2%)
[comments] 1074?p=3 -> 0 comments
[posts] 119/226 (52.7%)
[comments] 1073?p=3 -> 0 comments
[posts] 120/226 (53.1%)
[comments] 1072?p=3 -> 0 comments
[posts] 121/226 (53.5%)
[comments] 1071?p=3 -> 0 comments
[posts] 122/226 (54.0%)
[comments] 1070?p=3 -> 0 comments
[posts] 123/226 (54.4%)
[comments] 1069?p=3 -> 0 comments
[posts] 124/226 (54.9%)
[comments] 1068?p=3 -> 0 comments
[posts] 125/226 (55.3%)
[comments] 1067?p=3 -> 0 comments
[posts] 126/226 (55.8%)
[comments] 1066?p=3 -> 0 comments
[posts] 127/226 (56.2%)
[comments] 1065?p=3 -> 0 comments
[posts] 128/226 (56.6%)
[comments] 1064?p=3 -> 0 comments
[posts] 129/226 (57.1%)
[comments] 1063?p=3 -> 0 comments
[posts] 130/226 (57.5%)
[comments] 1062?p=3 -> 0 comments
[posts] 131/226 (58.0%)
[comments] 1061?p=3 -> 0 comments
[posts] 132/226 (58.4%)
[comments] 1060?p=3 -> 0 comments
[posts] 133/226 (58.8%)
[comments] 1059?p=3 -> 0 comments
[posts] 134/226 (59.3%)
[comments] 1057?p=3 -> 0 comments
[posts] 135/226 (59.7%)
[comments] 1056?p=3 -> 0 comments
[posts] 136/226 (60.2%)
[comments] 1055?p=3 -> 0 comments
[posts] 137/226 (60.6%)
[comments] 1054?p=4 -> 0 comments
[posts] 138/226 (61.1%)
[comments] 1053?p=4 -> 0 comments
[posts] 139/226 (61.5%)
[comments] 1052?p=4 -> 0 comments
[posts] 140/226 (61.9%)
[comments] 1051?p=4 -> 0 comments
[posts] 141/226 (62.4%)
[comments] 1050?p=4 -> 0 comments
[posts] 142/226 (62.8%)
[comments] 1049?p=4 -> 0 comments
[posts] 143/226 (63.3%)
[comments] 1048?p=4 -> 0 comments
[posts] 144/226 (63.7%)
[comments] 1047?p=4 -> 0 comments
[posts] 145/226 (64.2%)
[comments] 1046?p=4 -> 0 comments
[posts] 146/226 (64.6%)
[comments] 1045?p=4 -> 0 comments
[posts] 147/226 (65.0%)
[comments] 1044?p=4 -> 0 comments
[posts] 148/226 (65.5%)
[comments] 1043?p=4 -> 0 comments
[posts] 149/226 (65.9%)
[comments] 1042?p=4 -> 0 comments
[posts] 150/226 (66.4%)
[comments] 1041?p=4 -> 0 comments
[posts] 151/226 (66.8%)
[comments] 1040?p=4 -> 0 comments
[posts] 152/226 (67.3%)
[comments] 1039?p=4 -> 0 comments
[posts] 153/226 (67.7%)
[comments] 1038?p=4 -> 0 comments
[posts] 154/226 (68.1%)
[comments] 1037?p=4 -> 0 comments
[posts] 155/226 (68.6%)
[comments] 1036?p=4 -> 0 comments
[posts] 156/226 (69.0%)
[comments] 1035?p=4 -> 0 comments
[posts] 157/226 (69.5%)
[comments] 1034?p=4 -> 0 comments
[posts] 158/226 (69.9%)
[comments] 1033?p=4 -> 0 comments
[posts] 159/226 (70.4%)
[comments] 1032?p=4 -> 0 comments
[posts] 160/226 (70.8%)
[comments] 1031?p=4 -> 0 comments
[posts] 161/226 (71.2%)
[comments] 1030?p=4 -> 0 comments
[posts] 162/226 (71.7%)
[comments] 1029?p=4 -> 0 comments
[posts] 163/226 (72.1%)
[comments] 1028?p=4 -> 0 comments
[posts] 164/226 (72.6%)
[comments] 1027?p=4 -> 0 comments
[posts] 165/226 (73.0%)
[comments] 1026?p=4 -> 0 comments
[posts] 166/226 (73.5%)
[comments] 1025?p=4 -> 0 comments
[posts] 167/226 (73.9%)
[comments] 1024?p=4 -> 0 comments
[posts] 168/226 (74.3%)
[comments] 1023?p=4 -> 0 comments
[posts] 169/226 (74.8%)
[comments] 1022?p=4 -> 0 comments
[posts] 170/226 (75.2%)
[comments] 1021?p=4 -> 0 comments
[posts] 171/226 (75.7%)
[comments] 1020?p=4 -> 0 comments
[posts] 172/226 (76.1%)
[comments] 1019?p=4 -> 0 comments
[posts] 173/226 (76.5%)
[comments] 1018?p=4 -> 0 comments
[posts] 174/226 (77.0%)
[comments] 1017?p=4 -> 0 comments
[posts] 175/226 (77.4%)
[comments] 1016?p=4 -> 0 comments
[posts] 176/226 (77.9%)
[comments] 1015?p=4 -> 0 comments
[posts] 177/226 (78.3%)
[comments] 1014?p=4 -> 0 comments
[posts] 178/226 (78.8%)
[comments] 1013?p=4 -> 0 comments
[posts] 179/226 (79.2%)
[comments] 1012?p=4 -> 0 comments
[posts] 180/226 (79.6%)
[comments] 1011?p=4 -> 0 comments
[posts] 181/226 (80.1%)
[comments] 1010?p=4 -> 0 comments
[posts] 182/226 (80.5%)
[comments] 1008?p=5 -> 0 comments
[posts] 183/226 (81.0%)
[comments] 1007?p=5 -> 0 comments
[posts] 184/226 (81.4%)
[comments] 1006?p=5 -> 0 comments
[posts] 185/226 (81.9%)
[comments] 1005?p=5 -> 0 comments
[posts] 186/226 (82.3%)
[comments] 1004?p=5 -> 0 comments
[posts] 187/226 (82.7%)
[comments] 1003?p=5 -> 0 comments
[posts] 188/226 (83.2%)
[comments] 1002?p=5 -> 0 comments
[posts] 189/226 (83.6%)
[comments] 1001?p=5 -> 0 comments
[posts] 190/226 (84.1%)
[comments] 1000?p=5 -> 0 comments
[posts] 191/226 (84.5%)
[comments] 999?p=5 -> 0 comments
[posts] 192/226 (85.0%)
[comments] 998?p=5 -> 0 comments
[posts] 193/226 (85.4%)
[comments] 996?p=5 -> 0 comments
[posts] 194/226 (85.8%)
[comments] 994?p=5 -> 0 comments
[posts] 195/226 (86.3%)
[comments] 993?p=5 -> 0 comments
[posts] 196/226 (86.7%)
[comments] 991?p=5 -> 0 comments
[posts] 197/226 (87.2%)
[comments] 990?p=5 -> 0 comments
[posts] 198/226 (87.6%)
[comments] 989?p=5 -> 0 comments
[posts] 199/226 (88.1%)
[comments] 988?p=5 -> 0 comments
[posts] 200/226 (88.5%)
[comments] 987?p=5 -> 0 comments
[posts] 201/226 (88.9%)
[comments] 986?p=5 -> 0 comments
[posts] 202/226 (89.4%)
[comments] 985?p=5 -> 0 comments
[posts] 203/226 (89.8%)
[comments] 984?p=5 -> 0 comments
[posts] 204/226 (90.3%)
[comments] 983?p=5 -> 0 comments
[posts] 205/226 (90.7%)
[comments] 982?p=5 -> 0 comments
[posts] 206/226 (91.2%)
[comments] 981?p=5 -> 0 comments
[posts] 207/226 (91.6%)
[comments] 980?p=5 -> 0 comments
[posts] 208/226 (92.0%)
[comments] 979?p=5 -> 0 comments
[posts] 209/226 (92.5%)
[comments] 978?p=5 -> 0 comments
[posts] 210/226 (92.9%)
[comments] 977?p=5 -> 0 comments
[posts] 211/226 (93.4%)
[comments] 976?p=5 -> 0 comments
[posts] 212/226 (93.8%)
[comments] 975?p=5 -> 0 comments
[posts] 213/226 (94.2%)
[comments] 974?p=5 -> 0 comments
[posts] 214/226 (94.7%)
[comments] 973?p=5 -> 0 comments
[posts] 215/226 (95.1%)
[comments] 972?p=5 -> 0 comments
[posts] 216/226 (95.6%)
[comments] 970?p=5 -> 0 comments
[posts] 217/226 (96.0%)
[comments] 969?p=5 -> 0 comments
[posts] 218/226 (96.5%)
[comments] 968?p=5 -> 0 comments
[posts] 219/226 (96.9%)
[comments] 967?p=5 -> 0 comments
[posts] 220/226 (97.3%)
[comments] 966?p=5 -> 0 comments
[posts] 221/226 (97.8%)
[comments] 965?p=5 -> 0 comments
[posts] 222/226 (98.2%)
[comments] 964?p=5 -> 0 comments
[posts] 223/226 (98.7%)
[comments] 963?p=5 -> 0 comments
[posts] 224/226 (99.1%)
[comments] 962?p=5 -> 0 comments
[posts] 225/226 (99.6%)
[comments] 961?p=5 -> 0 comments
[posts] 226/226 (100.0%)
[comments] 960?p=5 -> 0 comments
Saved inven_out\lostark_mobile\lostark_mobile_20260325.csv
[aion2] page 1/5
[aion2] page 2/5
[aion2] page 3/5
[aion2] page 4/5
[aion2] page 5/5
[aion2] total 325 posts
Saved inven_out\aion2\aion2_20260325.csv
Done crawling

In [4]:
import os
import json
import time
import random
from datetime import datetime
from typing import List, Dict, Any, Optional, Tuple

import requests
import pandas as pd
from bs4 import BeautifulSoup

In [11]:
"""===============================================
트러블 슈팅 : 아이온2 데이터 수집 오류 확인
원인 : 날짜 파싱 오류, 웹 크롤링 방식에서 URL 정상적으로 못 가져오는 현상, 인벤 게시판 구조가 다름

requests로 못 가져오고 브라우저 기반 수집(Selenium) 방법 선택
날짜 필터 유연화 (dateutil.parser)
중간 저장 (state.json) 적용
진행률 표시
CSV 저장
MAX_PAGES 확장 (2주치 게시글 확보)
==============================================="""
# import
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time
import os

BASE_URL = "https://www.inven.co.kr/board/aion2/6388"
HEADERS = {"User-Agent": "Mozilla/5.0"}

MAX_PAGE = 20
BASE_DIR = "inven_out/aion2"
os.makedirs(BASE_DIR, exist_ok=True)

def get_post_links(page):
    url = f"{BASE_URL}?page={page}"
    res = requests.get(url, headers=HEADERS)
    soup = BeautifulSoup(res.text, "html.parser")

    posts = []
    rows = soup.select("tr")

    for row in rows:
        title_tag = row.select_one("td.tit a.subject-link")
        if not title_tag:
            continue

        posts.append({
            "title": title_tag.text.strip(),
            "url": title_tag["href"]
        })

    return posts

def get_post_detail(post):
    res = requests.get(post["url"], headers=HEADERS)
    soup = BeautifulSoup(res.text, "html.parser")

    content_tag = soup.select_one(".contentBody")
    content = content_tag.text.strip() if content_tag else ""

    # 댓글
    comments = []
    comment_tags = soup.select(".cmtContent")
    for c in comment_tags:
        txt = c.text.strip()
        if txt:
            comments.append(txt)

    return {
        "title": post["title"],
        "content": content,
        "comments": comments,
        "url": post["url"],
        "comment_count": len(comments)
    }

# 전체 수집
all_posts = []

for page in range(1, MAX_PAGE + 1):
    print(f"[게시글] {page}/{MAX_PAGE} 페이지 수집 중 ({round(page/MAX_PAGE*100,1)}%)")

    posts = get_post_links(page)
    if not posts:
        print("게시글 없음 → 종료")
        break

    all_posts.extend(posts)
    time.sleep(1)

print(f"총 게시글 수: {len(all_posts)}")

# 상세 + 댓글 수집
final_data = []

total = len(all_posts)

for idx, post in enumerate(all_posts, 1):
    print(f"[댓글] {idx}/{total} ({round(idx/total*100,1)}%) 수집 중")

    detail = get_post_detail(post)

    if detail["comments"]:
        for c in detail["comments"]:
            final_data.append({
                "title": detail["title"],
                "content": detail["content"],
                "comment": c,
                "url": detail["url"],
                "comment_count": detail["comment_count"]
            })
    else:
        final_data.append({
            "title": detail["title"],
            "content": detail["content"],
            "comment": "",
            "url": detail["url"],
            "comment_count": detail["comment_count"]
        })

    time.sleep(0.5)

# 저장 
df = pd.DataFrame(final_data)

today = pd.Timestamp.now().strftime("%Y%m%d")
filename = os.path.join(BASE_DIR, f"aion2_{today}.csv")

df.to_csv(filename, index=False, encoding="utf-8-sig")

print(f"저장 완료: {filename}")

[게시글] 1/20 페이지 수집 중 (5.0%)
[게시글] 2/20 페이지 수집 중 (10.0%)
[게시글] 3/20 페이지 수집 중 (15.0%)
[게시글] 4/20 페이지 수집 중 (20.0%)
[게시글] 5/20 페이지 수집 중 (25.0%)
[게시글] 6/20 페이지 수집 중 (30.0%)
[게시글] 7/20 페이지 수집 중 (35.0%)
[게시글] 8/20 페이지 수집 중 (40.0%)
[게시글] 9/20 페이지 수집 중 (45.0%)
[게시글] 10/20 페이지 수집 중 (50.0%)
[게시글] 11/20 페이지 수집 중 (55.0%)
[게시글] 12/20 페이지 수집 중 (60.0%)
[게시글] 13/20 페이지 수집 중 (65.0%)
[게시글] 14/20 페이지 수집 중 (70.0%)
[게시글] 15/20 페이지 수집 중 (75.0%)
[게시글] 16/20 페이지 수집 중 (80.0%)
[게시글] 17/20 페이지 수집 중 (85.0%)
[게시글] 18/20 페이지 수집 중 (90.0%)
[게시글] 19/20 페이지 수집 중 (95.0%)
[게시글] 20/20 페이지 수집 중 (100.0%)
총 게시글 수: 1400
[댓글] 1/1400 (0.1%) 수집 중
[댓글] 2/1400 (0.1%) 수집 중
[댓글] 3/1400 (0.2%) 수집 중
[댓글] 4/1400 (0.3%) 수집 중
[댓글] 5/1400 (0.4%) 수집 중
[댓글] 6/1400 (0.4%) 수집 중
[댓글] 7/1400 (0.5%) 수집 중
[댓글] 8/1400 (0.6%) 수집 중
[댓글] 9/1400 (0.6%) 수집 중
[댓글] 10/1400 (0.7%) 수집 중
[댓글] 11/1400 (0.8%) 수집 중
[댓글] 12/1400 (0.9%) 수집 중
[댓글] 13/1400 (0.9%) 수집 중
[댓글] 14/1400 (1.0%) 수집 중
[댓글] 15/1400 (1.1%) 수집 중
[댓글] 16/1400 (1.1%) 수집 중
[댓글] 17/1400 (1.2%) 수집 중
[댓글] 18/1400 (1.3%) 수집 중
[댓글] 19/1400 (1.4%) 수집 중
[댓글] 20/1400 (1.4%) 수집 중
[댓글] 21/1400 (1.5%) 수집 중
[댓글] 22/1400 (1.6%) 수집 중
[댓글] 23/1400 (1.6%) 수집 중
[댓글] 24/1400 (1.7%) 수집 중
[댓글] 25/1400 (1.8%) 수집 중
[댓글] 26/1400 (1.9%) 수집 중
[댓글] 27/1400 (1.9%) 수집 중
[댓글] 28/1400 (2.0%) 수집 중
[댓글] 29/1400 (2.1%) 수집 중
[댓글] 30/1400 (2.1%) 수집 중
[댓글] 31/1400 (2.2%) 수집 중
[댓글] 32/1400 (2.3%) 수집 중
[댓글] 33/1400 (2.4%) 수집 중
[댓글] 34/1400 (2.4%) 수집 중
[댓글] 35/1400 (2.5%) 수집 중
[댓글] 36/1400 (2.6%) 수집 중
[댓글] 37/1400 (2.6%) 수집 중
[댓글] 38/1400 (2.7%) 수집 중
[댓글] 39/1400 (2.8%) 수집 중
[댓글] 40/1400 (2.9%) 수집 중
[댓글] 41/1400 (2.9%) 수집 중
[댓글] 42/1400 (3.0%) 수집 중
[댓글] 43/1400 (3.1%) 수집 중
[댓글] 44/1400 (3.1%) 수집 중
[댓글] 45/1400 (3.2%) 수집 중
[댓글] 46/1400 (3.3%) 수집 중
[댓글] 47/1400 (3.4%) 수집 중
[댓글] 48/1400 (3.4%) 수집 중
[댓글] 49/1400 (3.5%) 수집 중
[댓글] 50/1400 (3.6%) 수집 중
[댓글] 51/1400 (3.6%) 수집 중
[댓글] 52/1400 (3.7%) 수집 중
[댓글] 53/1400 (3.8%) 수집 중
[댓글] 54/1400 (3.9%) 수집 중
[댓글] 55/1400 (3.9%) 수집 중
[댓글] 56/1400 (4.0%) 수집 중
[댓글] 57/1400 (4.1%) 수집 중
[댓글] 58/1400 (4.1%) 수집 중
[댓글] 59/1400 (4.2%) 수집 중
[댓글] 60/1400 (4.3%) 수집 중
[댓글] 61/1400 (4.4%) 수집 중
[댓글] 62/1400 (4.4%) 수집 중
[댓글] 63/1400 (4.5%) 수집 중
[댓글] 64/1400 (4.6%) 수집 중
[댓글] 65/1400 (4.6%) 수집 중
[댓글] 66/1400 (4.7%) 수집 중
[댓글] 67/1400 (4.8%) 수집 중
[댓글] 68/1400 (4.9%) 수집 중
[댓글] 69/1400 (4.9%) 수집 중
[댓글] 70/1400 (5.0%) 수집 중
[댓글] 71/1400 (5.1%) 수집 중
[댓글] 72/1400 (5.1%) 수집 중
[댓글] 73/1400 (5.2%) 수집 중
[댓글] 74/1400 (5.3%) 수집 중
[댓글] 75/1400 (5.4%) 수집 중
[댓글] 76/1400 (5.4%) 수집 중
[댓글] 77/1400 (5.5%) 수집 중
[댓글] 78/1400 (5.6%) 수집 중
[댓글] 79/1400 (5.6%) 수집 중
[댓글] 80/1400 (5.7%) 수집 중
[댓글] 81/1400 (5.8%) 수집 중
[댓글] 82/1400 (5.9%) 수집 중
[댓글] 83/1400 (5.9%) 수집 중
[댓글] 84/1400 (6.0%) 수집 중
[댓글] 85/1400 (6.1%) 수집 중
[댓글] 86/1400 (6.1%) 수집 중
[댓글] 87/1400 (6.2%) 수집 중
[댓글] 88/1400 (6.3%) 수집 중
[댓글] 89/1400 (6.4%) 수집 중
[댓글] 90/1400 (6.4%) 수집 중
[댓글] 91/1400 (6.5%) 수집 중
[댓글] 92/1400 (6.6%) 수집 중
[댓글] 93/1400 (6.6%) 수집 중
[댓글] 94/1400 (6.7%) 수집 중
[댓글] 95/1400 (6.8%) 수집 중
[댓글] 96/1400 (6.9%) 수집 중
[댓글] 97/1400 (6.9%) 수집 중
[댓글] 98/1400 (7.0%) 수집 중
[댓글] 99/1400 (7.1%) 수집 중
[댓글] 100/1400 (7.1%) 수집 중
[댓글] 101/1400 (7.2%) 수집 중
[댓글] 102/1400 (7.3%) 수집 중
[댓글] 103/1400 (7.4%) 수집 중
[댓글] 104/1400 (7.4%) 수집 중
[댓글] 105/1400 (7.5%) 수집 중
[댓글] 106/1400 (7.6%) 수집 중
[댓글] 107/1400 (7.6%) 수집 중
[댓글] 108/1400 (7.7%) 수집 중
[댓글] 109/1400 (7.8%) 수집 중
[댓글] 110/1400 (7.9%) 수집 중
[댓글] 111/1400 (7.9%) 수집 중
[댓글] 112/1400 (8.0%) 수집 중
[댓글] 113/1400 (8.1%) 수집 중
[댓글] 114/1400 (8.1%) 수집 중
[댓글] 115/1400 (8.2%) 수집 중
[댓글] 116/1400 (8.3%) 수집 중
[댓글] 117/1400 (8.4%) 수집 중
[댓글] 118/1400 (8.4%) 수집 중
[댓글] 119/1400 (8.5%) 수집 중
[댓글] 120/1400 (8.6%) 수집 중
[댓글] 121/1400 (8.6%) 수집 중
[댓글] 122/1400 (8.7%) 수집 중
[댓글] 123/1400 (8.8%) 수집 중
[댓글] 124/1400 (8.9%) 수집 중
[댓글] 125/1400 (8.9%) 수집 중
[댓글] 126/1400 (9.0%) 수집 중
[댓글] 127/1400 (9.1%) 수집 중
[댓글] 128/1400 (9.1%) 수집 중
[댓글] 129/1400 (9.2%) 수집 중
[댓글] 130/1400 (9.3%) 수집 중
[댓글] 131/1400 (9.4%) 수집 중
[댓글] 132/1400 (9.4%) 수집 중
[댓글] 133/1400 (9.5%) 수집 중
[댓글] 134/1400 (9.6%) 수집 중
[댓글] 135/1400 (9.6%) 수집 중
[댓글] 136/1400 (9.7%) 수집 중
[댓글] 137/1400 (9.8%) 수집 중
[댓글] 138/1400 (9.9%) 수집 중
[댓글] 139/1400 (9.9%) 수집 중
[댓글] 140/1400 (10.0%) 수집 중
[댓글] 141/1400 (10.1%) 수집 중
[댓글] 142/1400 (10.1%) 수집 중
[댓글] 143/1400 (10.2%) 수집 중
[댓글] 144/1400 (10.3%) 수집 중
[댓글] 145/1400 (10.4%) 수집 중
[댓글] 146/1400 (10.4%) 수집 중
[댓글] 147/1400 (10.5%) 수집 중
[댓글] 148/1400 (10.6%) 수집 중
[댓글] 149/1400 (10.6%) 수집 중
[댓글] 150/1400 (10.7%) 수집 중
[댓글] 151/1400 (10.8%) 수집 중
[댓글] 152/1400 (10.9%) 수집 중
[댓글] 153/1400 (10.9%) 수집 중
[댓글] 154/1400 (11.0%) 수집 중
[댓글] 155/1400 (11.1%) 수집 중
[댓글] 156/1400 (11.1%) 수집 중
[댓글] 157/1400 (11.2%) 수집 중
[댓글] 158/1400 (11.3%) 수집 중
[댓글] 159/1400 (11.4%) 수집 중
[댓글] 160/1400 (11.4%) 수집 중
[댓글] 161/1400 (11.5%) 수집 중
[댓글] 162/1400 (11.6%) 수집 중
[댓글] 163/1400 (11.6%) 수집 중
[댓글] 164/1400 (11.7%) 수집 중
[댓글] 165/1400 (11.8%) 수집 중
[댓글] 166/1400 (11.9%) 수집 중
[댓글] 167/1400 (11.9%) 수집 중
[댓글] 168/1400 (12.0%) 수집 중
[댓글] 169/1400 (12.1%) 수집 중
[댓글] 170/1400 (12.1%) 수집 중
[댓글] 171/1400 (12.2%) 수집 중
[댓글] 172/1400 (12.3%) 수집 중
[댓글] 173/1400 (12.4%) 수집 중
[댓글] 174/1400 (12.4%) 수집 중
[댓글] 175/1400 (12.5%) 수집 중
[댓글] 176/1400 (12.6%) 수집 중
[댓글] 177/1400 (12.6%) 수집 중
[댓글] 178/1400 (12.7%) 수집 중
[댓글] 179/1400 (12.8%) 수집 중
[댓글] 180/1400 (12.9%) 수집 중
[댓글] 181/1400 (12.9%) 수집 중
[댓글] 182/1400 (13.0%) 수집 중
[댓글] 183/1400 (13.1%) 수집 중
[댓글] 184/1400 (13.1%) 수집 중
[댓글] 185/1400 (13.2%) 수집 중
[댓글] 186/1400 (13.3%) 수집 중
[댓글] 187/1400 (13.4%) 수집 중
[댓글] 188/1400 (13.4%) 수집 중
[댓글] 189/1400 (13.5%) 수집 중
[댓글] 190/1400 (13.6%) 수집 중
[댓글] 191/1400 (13.6%) 수집 중
[댓글] 192/1400 (13.7%) 수집 중
[댓글] 193/1400 (13.8%) 수집 중
[댓글] 194/1400 (13.9%) 수집 중
[댓글] 195/1400 (13.9%) 수집 중
[댓글] 196/1400 (14.0%) 수집 중
[댓글] 197/1400 (14.1%) 수집 중
[댓글] 198/1400 (14.1%) 수집 중
[댓글] 199/1400 (14.2%) 수집 중
[댓글] 200/1400 (14.3%) 수집 중
[댓글] 201/1400 (14.4%) 수집 중
[댓글] 202/1400 (14.4%) 수집 중
[댓글] 203/1400 (14.5%) 수집 중
[댓글] 204/1400 (14.6%) 수집 중
[댓글] 205/1400 (14.6%) 수집 중
[댓글] 206/1400 (14.7%) 수집 중
[댓글] 207/1400 (14.8%) 수집 중
[댓글] 208/1400 (14.9%) 수집 중
[댓글] 209/1400 (14.9%) 수집 중
[댓글] 210/1400 (15.0%) 수집 중
[댓글] 211/1400 (15.1%) 수집 중
[댓글] 212/1400 (15.1%) 수집 중
[댓글] 213/1400 (15.2%) 수집 중
[댓글] 214/1400 (15.3%) 수집 중
[댓글] 215/1400 (15.4%) 수집 중
[댓글] 216/1400 (15.4%) 수집 중
[댓글] 217/1400 (15.5%) 수집 중
[댓글] 218/1400 (15.6%) 수집 중
[댓글] 219/1400 (15.6%) 수집 중
[댓글] 220/1400 (15.7%) 수집 중
[댓글] 221/1400 (15.8%) 수집 중
[댓글] 222/1400 (15.9%) 수집 중
[댓글] 223/1400 (15.9%) 수집 중
[댓글] 224/1400 (16.0%) 수집 중
[댓글] 225/1400 (16.1%) 수집 중
[댓글] 226/1400 (16.1%) 수집 중
[댓글] 227/1400 (16.2%) 수집 중
[댓글] 228/1400 (16.3%) 수집 중
[댓글] 229/1400 (16.4%) 수집 중
[댓글] 230/1400 (16.4%) 수집 중
[댓글] 231/1400 (16.5%) 수집 중
[댓글] 232/1400 (16.6%) 수집 중
[댓글] 233/1400 (16.6%) 수집 중
[댓글] 234/1400 (16.7%) 수집 중
[댓글] 235/1400 (16.8%) 수집 중
[댓글] 236/1400 (16.9%) 수집 중
[댓글] 237/1400 (16.9%) 수집 중
[댓글] 238/1400 (17.0%) 수집 중
[댓글] 239/1400 (17.1%) 수집 중
[댓글] 240/1400 (17.1%) 수집 중
[댓글] 241/1400 (17.2%) 수집 중
[댓글] 242/1400 (17.3%) 수집 중
[댓글] 243/1400 (17.4%) 수집 중
[댓글] 244/1400 (17.4%) 수집 중
[댓글] 245/1400 (17.5%) 수집 중
[댓글] 246/1400 (17.6%) 수집 중
[댓글] 247/1400 (17.6%) 수집 중
[댓글] 248/1400 (17.7%) 수집 중
[댓글] 249/1400 (17.8%) 수집 중
[댓글] 250/1400 (17.9%) 수집 중
[댓글] 251/1400 (17.9%) 수집 중
[댓글] 252/1400 (18.0%) 수집 중
[댓글] 253/1400 (18.1%) 수집 중
[댓글] 254/1400 (18.1%) 수집 중
[댓글] 255/1400 (18.2%) 수집 중
[댓글] 256/1400 (18.3%) 수집 중
[댓글] 257/1400 (18.4%) 수집 중
[댓글] 258/1400 (18.4%) 수집 중
[댓글] 259/1400 (18.5%) 수집 중
[댓글] 260/1400 (18.6%) 수집 중
[댓글] 261/1400 (18.6%) 수집 중
[댓글] 262/1400 (18.7%) 수집 중
[댓글] 263/1400 (18.8%) 수집 중
[댓글] 264/1400 (18.9%) 수집 중
[댓글] 265/1400 (18.9%) 수집 중
[댓글] 266/1400 (19.0%) 수집 중
[댓글] 267/1400 (19.1%) 수집 중
[댓글] 268/1400 (19.1%) 수집 중
[댓글] 269/1400 (19.2%) 수집 중
[댓글] 270/1400 (19.3%) 수집 중
[댓글] 271/1400 (19.4%) 수집 중
[댓글] 272/1400 (19.4%) 수집 중
[댓글] 273/1400 (19.5%) 수집 중
[댓글] 274/1400 (19.6%) 수집 중
[댓글] 275/1400 (19.6%) 수집 중
[댓글] 276/1400 (19.7%) 수집 중
[댓글] 277/1400 (19.8%) 수집 중
[댓글] 278/1400 (19.9%) 수집 중
[댓글] 279/1400 (19.9%) 수집 중
[댓글] 280/1400 (20.0%) 수집 중
[댓글] 281/1400 (20.1%) 수집 중
[댓글] 282/1400 (20.1%) 수집 중
[댓글] 283/1400 (20.2%) 수집 중
[댓글] 284/1400 (20.3%) 수집 중
[댓글] 285/1400 (20.4%) 수집 중
[댓글] 286/1400 (20.4%) 수집 중
[댓글] 287/1400 (20.5%) 수집 중
[댓글] 288/1400 (20.6%) 수집 중
[댓글] 289/1400 (20.6%) 수집 중
[댓글] 290/1400 (20.7%) 수집 중
[댓글] 291/1400 (20.8%) 수집 중
[댓글] 292/1400 (20.9%) 수집 중
[댓글] 293/1400 (20.9%) 수집 중
[댓글] 294/1400 (21.0%) 수집 중
[댓글] 295/1400 (21.1%) 수집 중
[댓글] 296/1400 (21.1%) 수집 중
[댓글] 297/1400 (21.2%) 수집 중
[댓글] 298/1400 (21.3%) 수집 중
[댓글] 299/1400 (21.4%) 수집 중
[댓글] 300/1400 (21.4%) 수집 중
[댓글] 301/1400 (21.5%) 수집 중
[댓글] 302/1400 (21.6%) 수집 중
[댓글] 303/1400 (21.6%) 수집 중
[댓글] 304/1400 (21.7%) 수집 중
[댓글] 305/1400 (21.8%) 수집 중
[댓글] 306/1400 (21.9%) 수집 중
[댓글] 307/1400 (21.9%) 수집 중
[댓글] 308/1400 (22.0%) 수집 중
[댓글] 309/1400 (22.1%) 수집 중
[댓글] 310/1400 (22.1%) 수집 중
[댓글] 311/1400 (22.2%) 수집 중
[댓글] 312/1400 (22.3%) 수집 중
[댓글] 313/1400 (22.4%) 수집 중
[댓글] 314/1400 (22.4%) 수집 중
[댓글] 315/1400 (22.5%) 수집 중
[댓글] 316/1400 (22.6%) 수집 중
[댓글] 317/1400 (22.6%) 수집 중
[댓글] 318/1400 (22.7%) 수집 중
[댓글] 319/1400 (22.8%) 수집 중
[댓글] 320/1400 (22.9%) 수집 중
[댓글] 321/1400 (22.9%) 수집 중
[댓글] 322/1400 (23.0%) 수집 중
[댓글] 323/1400 (23.1%) 수집 중
[댓글] 324/1400 (23.1%) 수집 중
[댓글] 325/1400 (23.2%) 수집 중
[댓글] 326/1400 (23.3%) 수집 중
[댓글] 327/1400 (23.4%) 수집 중
[댓글] 328/1400 (23.4%) 수집 중
[댓글] 329/1400 (23.5%) 수집 중
[댓글] 330/1400 (23.6%) 수집 중
[댓글] 331/1400 (23.6%) 수집 중
[댓글] 332/1400 (23.7%) 수집 중
[댓글] 333/1400 (23.8%) 수집 중
[댓글] 334/1400 (23.9%) 수집 중
[댓글] 335/1400 (23.9%) 수집 중
[댓글] 336/1400 (24.0%) 수집 중
[댓글] 337/1400 (24.1%) 수집 중
[댓글] 338/1400 (24.1%) 수집 중
[댓글] 339/1400 (24.2%) 수집 중
[댓글] 340/1400 (24.3%) 수집 중
[댓글] 341/1400 (24.4%) 수집 중
[댓글] 342/1400 (24.4%) 수집 중
[댓글] 343/1400 (24.5%) 수집 중
[댓글] 344/1400 (24.6%) 수집 중
[댓글] 345/1400 (24.6%) 수집 중
[댓글] 346/1400 (24.7%) 수집 중
[댓글] 347/1400 (24.8%) 수집 중
[댓글] 348/1400 (24.9%) 수집 중
[댓글] 349/1400 (24.9%) 수집 중
[댓글] 350/1400 (25.0%) 수집 중
[댓글] 351/1400 (25.1%) 수집 중
[댓글] 352/1400 (25.1%) 수집 중
[댓글] 353/1400 (25.2%) 수집 중
[댓글] 354/1400 (25.3%) 수집 중
[댓글] 355/1400 (25.4%) 수집 중
[댓글] 356/1400 (25.4%) 수집 중
[댓글] 357/1400 (25.5%) 수집 중
[댓글] 358/1400 (25.6%) 수집 중
[댓글] 359/1400 (25.6%) 수집 중
[댓글] 360/1400 (25.7%) 수집 중
[댓글] 361/1400 (25.8%) 수집 중
[댓글] 362/1400 (25.9%) 수집 중
[댓글] 363/1400 (25.9%) 수집 중
[댓글] 364/1400 (26.0%) 수집 중
[댓글] 365/1400 (26.1%) 수집 중
[댓글] 366/1400 (26.1%) 수집 중
[댓글] 367/1400 (26.2%) 수집 중
[댓글] 368/1400 (26.3%) 수집 중
[댓글] 369/1400 (26.4%) 수집 중
[댓글] 370/1400 (26.4%) 수집 중
[댓글] 371/1400 (26.5%) 수집 중
[댓글] 372/1400 (26.6%) 수집 중
[댓글] 373/1400 (26.6%) 수집 중
[댓글] 374/1400 (26.7%) 수집 중
[댓글] 375/1400 (26.8%) 수집 중
[댓글] 376/1400 (26.9%) 수집 중
[댓글] 377/1400 (26.9%) 수집 중
[댓글] 378/1400 (27.0%) 수집 중
[댓글] 379/1400 (27.1%) 수집 중
[댓글] 380/1400 (27.1%) 수집 중
[댓글] 381/1400 (27.2%) 수집 중
[댓글] 382/1400 (27.3%) 수집 중
[댓글] 383/1400 (27.4%) 수집 중
[댓글] 384/1400 (27.4%) 수집 중
[댓글] 385/1400 (27.5%) 수집 중
[댓글] 386/1400 (27.6%) 수집 중
[댓글] 387/1400 (27.6%) 수집 중
[댓글] 388/1400 (27.7%) 수집 중
[댓글] 389/1400 (27.8%) 수집 중
[댓글] 390/1400 (27.9%) 수집 중
[댓글] 391/1400 (27.9%) 수집 중
[댓글] 392/1400 (28.0%) 수집 중
[댓글] 393/1400 (28.1%) 수집 중
[댓글] 394/1400 (28.1%) 수집 중
[댓글] 395/1400 (28.2%) 수집 중
[댓글] 396/1400 (28.3%) 수집 중
[댓글] 397/1400 (28.4%) 수집 중
[댓글] 398/1400 (28.4%) 수집 중
[댓글] 399/1400 (28.5%) 수집 중
[댓글] 400/1400 (28.6%) 수집 중
[댓글] 401/1400 (28.6%) 수집 중
[댓글] 402/1400 (28.7%) 수집 중
[댓글] 403/1400 (28.8%) 수집 중
[댓글] 404/1400 (28.9%) 수집 중
[댓글] 405/1400 (28.9%) 수집 중
[댓글] 406/1400 (29.0%) 수집 중
[댓글] 407/1400 (29.1%) 수집 중
[댓글] 408/1400 (29.1%) 수집 중
[댓글] 409/1400 (29.2%) 수집 중
[댓글] 410/1400 (29.3%) 수집 중
[댓글] 411/1400 (29.4%) 수집 중
[댓글] 412/1400 (29.4%) 수집 중
[댓글] 413/1400 (29.5%) 수집 중
[댓글] 414/1400 (29.6%) 수집 중
[댓글] 415/1400 (29.6%) 수집 중
[댓글] 416/1400 (29.7%) 수집 중
[댓글] 417/1400 (29.8%) 수집 중
[댓글] 418/1400 (29.9%) 수집 중
[댓글] 419/1400 (29.9%) 수집 중
[댓글] 420/1400 (30.0%) 수집 중
[댓글] 421/1400 (30.1%) 수집 중
[댓글] 422/1400 (30.1%) 수집 중
[댓글] 423/1400 (30.2%) 수집 중
[댓글] 424/1400 (30.3%) 수집 중
[댓글] 425/1400 (30.4%) 수집 중
[댓글] 426/1400 (30.4%) 수집 중
[댓글] 427/1400 (30.5%) 수집 중
[댓글] 428/1400 (30.6%) 수집 중
[댓글] 429/1400 (30.6%) 수집 중
[댓글] 430/1400 (30.7%) 수집 중
[댓글] 431/1400 (30.8%) 수집 중
[댓글] 432/1400 (30.9%) 수집 중
[댓글] 433/1400 (30.9%) 수집 중
[댓글] 434/1400 (31.0%) 수집 중
[댓글] 435/1400 (31.1%) 수집 중
[댓글] 436/1400 (31.1%) 수집 중
[댓글] 437/1400 (31.2%) 수집 중
[댓글] 438/1400 (31.3%) 수집 중
[댓글] 439/1400 (31.4%) 수집 중
[댓글] 440/1400 (31.4%) 수집 중
[댓글] 441/1400 (31.5%) 수집 중
[댓글] 442/1400 (31.6%) 수집 중
[댓글] 443/1400 (31.6%) 수집 중
[댓글] 444/1400 (31.7%) 수집 중
[댓글] 445/1400 (31.8%) 수집 중
[댓글] 446/1400 (31.9%) 수집 중
[댓글] 447/1400 (31.9%) 수집 중
[댓글] 448/1400 (32.0%) 수집 중
[댓글] 449/1400 (32.1%) 수집 중
[댓글] 450/1400 (32.1%) 수집 중
[댓글] 451/1400 (32.2%) 수집 중
[댓글] 452/1400 (32.3%) 수집 중
[댓글] 453/1400 (32.4%) 수집 중
[댓글] 454/1400 (32.4%) 수집 중
[댓글] 455/1400 (32.5%) 수집 중
[댓글] 456/1400 (32.6%) 수집 중
[댓글] 457/1400 (32.6%) 수집 중
[댓글] 458/1400 (32.7%) 수집 중
[댓글] 459/1400 (32.8%) 수집 중
[댓글] 460/1400 (32.9%) 수집 중
[댓글] 461/1400 (32.9%) 수집 중
[댓글] 462/1400 (33.0%) 수집 중
[댓글] 463/1400 (33.1%) 수집 중
[댓글] 464/1400 (33.1%) 수집 중
[댓글] 465/1400 (33.2%) 수집 중
[댓글] 466/1400 (33.3%) 수집 중
[댓글] 467/1400 (33.4%) 수집 중
[댓글] 468/1400 (33.4%) 수집 중
[댓글] 469/1400 (33.5%) 수집 중
[댓글] 470/1400 (33.6%) 수집 중
[댓글] 471/1400 (33.6%) 수집 중
[댓글] 472/1400 (33.7%) 수집 중
[댓글] 473/1400 (33.8%) 수집 중
[댓글] 474/1400 (33.9%) 수집 중
[댓글] 475/1400 (33.9%) 수집 중
[댓글] 476/1400 (34.0%) 수집 중
[댓글] 477/1400 (34.1%) 수집 중
[댓글] 478/1400 (34.1%) 수집 중
[댓글] 479/1400 (34.2%) 수집 중
[댓글] 480/1400 (34.3%) 수집 중
[댓글] 481/1400 (34.4%) 수집 중
[댓글] 482/1400 (34.4%) 수집 중
[댓글] 483/1400 (34.5%) 수집 중
[댓글] 484/1400 (34.6%) 수집 중
[댓글] 485/1400 (34.6%) 수집 중
[댓글] 486/1400 (34.7%) 수집 중
[댓글] 487/1400 (34.8%) 수집 중
[댓글] 488/1400 (34.9%) 수집 중
[댓글] 489/1400 (34.9%) 수집 중
[댓글] 490/1400 (35.0%) 수집 중
[댓글] 491/1400 (35.1%) 수집 중
[댓글] 492/1400 (35.1%) 수집 중
[댓글] 493/1400 (35.2%) 수집 중
[댓글] 494/1400 (35.3%) 수집 중
[댓글] 495/1400 (35.4%) 수집 중
[댓글] 496/1400 (35.4%) 수집 중
[댓글] 497/1400 (35.5%) 수집 중
[댓글] 498/1400 (35.6%) 수집 중
[댓글] 499/1400 (35.6%) 수집 중
[댓글] 500/1400 (35.7%) 수집 중
[댓글] 501/1400 (35.8%) 수집 중
[댓글] 502/1400 (35.9%) 수집 중
[댓글] 503/1400 (35.9%) 수집 중
[댓글] 504/1400 (36.0%) 수집 중
[댓글] 505/1400 (36.1%) 수집 중
[댓글] 506/1400 (36.1%) 수집 중
[댓글] 507/1400 (36.2%) 수집 중
[댓글] 508/1400 (36.3%) 수집 중
[댓글] 509/1400 (36.4%) 수집 중
[댓글] 510/1400 (36.4%) 수집 중
[댓글] 511/1400 (36.5%) 수집 중
[댓글] 512/1400 (36.6%) 수집 중
[댓글] 513/1400 (36.6%) 수집 중
[댓글] 514/1400 (36.7%) 수집 중
[댓글] 515/1400 (36.8%) 수집 중
[댓글] 516/1400 (36.9%) 수집 중
[댓글] 517/1400 (36.9%) 수집 중
[댓글] 518/1400 (37.0%) 수집 중
[댓글] 519/1400 (37.1%) 수집 중
[댓글] 520/1400 (37.1%) 수집 중
[댓글] 521/1400 (37.2%) 수집 중
[댓글] 522/1400 (37.3%) 수집 중
[댓글] 523/1400 (37.4%) 수집 중
[댓글] 524/1400 (37.4%) 수집 중
[댓글] 525/1400 (37.5%) 수집 중
[댓글] 526/1400 (37.6%) 수집 중
[댓글] 527/1400 (37.6%) 수집 중
[댓글] 528/1400 (37.7%) 수집 중
[댓글] 529/1400 (37.8%) 수집 중
[댓글] 530/1400 (37.9%) 수집 중
[댓글] 531/1400 (37.9%) 수집 중
[댓글] 532/1400 (38.0%) 수집 중
[댓글] 533/1400 (38.1%) 수집 중
[댓글] 534/1400 (38.1%) 수집 중
[댓글] 535/1400 (38.2%) 수집 중
[댓글] 536/1400 (38.3%) 수집 중
[댓글] 537/1400 (38.4%) 수집 중
[댓글] 538/1400 (38.4%) 수집 중
[댓글] 539/1400 (38.5%) 수집 중
[댓글] 540/1400 (38.6%) 수집 중
[댓글] 541/1400 (38.6%) 수집 중
[댓글] 542/1400 (38.7%) 수집 중
[댓글] 543/1400 (38.8%) 수집 중
[댓글] 544/1400 (38.9%) 수집 중
[댓글] 545/1400 (38.9%) 수집 중
[댓글] 546/1400 (39.0%) 수집 중
[댓글] 547/1400 (39.1%) 수집 중
[댓글] 548/1400 (39.1%) 수집 중
[댓글] 549/1400 (39.2%) 수집 중
[댓글] 550/1400 (39.3%) 수집 중
[댓글] 551/1400 (39.4%) 수집 중
[댓글] 552/1400 (39.4%) 수집 중
[댓글] 553/1400 (39.5%) 수집 중
[댓글] 554/1400 (39.6%) 수집 중
[댓글] 555/1400 (39.6%) 수집 중
[댓글] 556/1400 (39.7%) 수집 중
[댓글] 557/1400 (39.8%) 수집 중
[댓글] 558/1400 (39.9%) 수집 중
[댓글] 559/1400 (39.9%) 수집 중
[댓글] 560/1400 (40.0%) 수집 중
[댓글] 561/1400 (40.1%) 수집 중
[댓글] 562/1400 (40.1%) 수집 중
[댓글] 563/1400 (40.2%) 수집 중
[댓글] 564/1400 (40.3%) 수집 중
[댓글] 565/1400 (40.4%) 수집 중
[댓글] 566/1400 (40.4%) 수집 중
[댓글] 567/1400 (40.5%) 수집 중
[댓글] 568/1400 (40.6%) 수집 중
[댓글] 569/1400 (40.6%) 수집 중
[댓글] 570/1400 (40.7%) 수집 중
[댓글] 571/1400 (40.8%) 수집 중
[댓글] 572/1400 (40.9%) 수집 중
[댓글] 573/1400 (40.9%) 수집 중
[댓글] 574/1400 (41.0%) 수집 중
[댓글] 575/1400 (41.1%) 수집 중
[댓글] 576/1400 (41.1%) 수집 중
[댓글] 577/1400 (41.2%) 수집 중
[댓글] 578/1400 (41.3%) 수집 중
[댓글] 579/1400 (41.4%) 수집 중
[댓글] 580/1400 (41.4%) 수집 중
[댓글] 581/1400 (41.5%) 수집 중
[댓글] 582/1400 (41.6%) 수집 중
[댓글] 583/1400 (41.6%) 수집 중
[댓글] 584/1400 (41.7%) 수집 중
[댓글] 585/1400 (41.8%) 수집 중
[댓글] 586/1400 (41.9%) 수집 중
[댓글] 587/1400 (41.9%) 수집 중
[댓글] 588/1400 (42.0%) 수집 중
[댓글] 589/1400 (42.1%) 수집 중
[댓글] 590/1400 (42.1%) 수집 중
[댓글] 591/1400 (42.2%) 수집 중
[댓글] 592/1400 (42.3%) 수집 중
[댓글] 593/1400 (42.4%) 수집 중
[댓글] 594/1400 (42.4%) 수집 중
[댓글] 595/1400 (42.5%) 수집 중
[댓글] 596/1400 (42.6%) 수집 중
[댓글] 597/1400 (42.6%) 수집 중
[댓글] 598/1400 (42.7%) 수집 중
[댓글] 599/1400 (42.8%) 수집 중
[댓글] 600/1400 (42.9%) 수집 중
[댓글] 601/1400 (42.9%) 수집 중
[댓글] 602/1400 (43.0%) 수집 중
[댓글] 603/1400 (43.1%) 수집 중
[댓글] 604/1400 (43.1%) 수집 중
[댓글] 605/1400 (43.2%) 수집 중
[댓글] 606/1400 (43.3%) 수집 중
[댓글] 607/1400 (43.4%) 수집 중
[댓글] 608/1400 (43.4%) 수집 중
[댓글] 609/1400 (43.5%) 수집 중
[댓글] 610/1400 (43.6%) 수집 중
[댓글] 611/1400 (43.6%) 수집 중
[댓글] 612/1400 (43.7%) 수집 중
[댓글] 613/1400 (43.8%) 수집 중
[댓글] 614/1400 (43.9%) 수집 중
[댓글] 615/1400 (43.9%) 수집 중
[댓글] 616/1400 (44.0%) 수집 중
[댓글] 617/1400 (44.1%) 수집 중
[댓글] 618/1400 (44.1%) 수집 중
[댓글] 619/1400 (44.2%) 수집 중
[댓글] 620/1400 (44.3%) 수집 중
[댓글] 621/1400 (44.4%) 수집 중
[댓글] 622/1400 (44.4%) 수집 중
[댓글] 623/1400 (44.5%) 수집 중
[댓글] 624/1400 (44.6%) 수집 중
[댓글] 625/1400 (44.6%) 수집 중
[댓글] 626/1400 (44.7%) 수집 중
[댓글] 627/1400 (44.8%) 수집 중
[댓글] 628/1400 (44.9%) 수집 중
[댓글] 629/1400 (44.9%) 수집 중
[댓글] 630/1400 (45.0%) 수집 중
[댓글] 631/1400 (45.1%) 수집 중
[댓글] 632/1400 (45.1%) 수집 중
[댓글] 633/1400 (45.2%) 수집 중
[댓글] 634/1400 (45.3%) 수집 중
[댓글] 635/1400 (45.4%) 수집 중
[댓글] 636/1400 (45.4%) 수집 중
[댓글] 637/1400 (45.5%) 수집 중
[댓글] 638/1400 (45.6%) 수집 중
[댓글] 639/1400 (45.6%) 수집 중
[댓글] 640/1400 (45.7%) 수집 중
[댓글] 641/1400 (45.8%) 수집 중
[댓글] 642/1400 (45.9%) 수집 중
[댓글] 643/1400 (45.9%) 수집 중
[댓글] 644/1400 (46.0%) 수집 중
[댓글] 645/1400 (46.1%) 수집 중
[댓글] 646/1400 (46.1%) 수집 중
[댓글] 647/1400 (46.2%) 수집 중
[댓글] 648/1400 (46.3%) 수집 중
[댓글] 649/1400 (46.4%) 수집 중
[댓글] 650/1400 (46.4%) 수집 중
[댓글] 651/1400 (46.5%) 수집 중
[댓글] 652/1400 (46.6%) 수집 중
[댓글] 653/1400 (46.6%) 수집 중
[댓글] 654/1400 (46.7%) 수집 중
[댓글] 655/1400 (46.8%) 수집 중
[댓글] 656/1400 (46.9%) 수집 중
[댓글] 657/1400 (46.9%) 수집 중
[댓글] 658/1400 (47.0%) 수집 중
[댓글] 659/1400 (47.1%) 수집 중
[댓글] 660/1400 (47.1%) 수집 중
[댓글] 661/1400 (47.2%) 수집 중
[댓글] 662/1400 (47.3%) 수집 중
[댓글] 663/1400 (47.4%) 수집 중
[댓글] 664/1400 (47.4%) 수집 중
[댓글] 665/1400 (47.5%) 수집 중
[댓글] 666/1400 (47.6%) 수집 중
[댓글] 667/1400 (47.6%) 수집 중
[댓글] 668/1400 (47.7%) 수집 중
[댓글] 669/1400 (47.8%) 수집 중
[댓글] 670/1400 (47.9%) 수집 중
[댓글] 671/1400 (47.9%) 수집 중
[댓글] 672/1400 (48.0%) 수집 중
[댓글] 673/1400 (48.1%) 수집 중
[댓글] 674/1400 (48.1%) 수집 중
[댓글] 675/1400 (48.2%) 수집 중
[댓글] 676/1400 (48.3%) 수집 중
[댓글] 677/1400 (48.4%) 수집 중
[댓글] 678/1400 (48.4%) 수집 중
[댓글] 679/1400 (48.5%) 수집 중
[댓글] 680/1400 (48.6%) 수집 중
[댓글] 681/1400 (48.6%) 수집 중
[댓글] 682/1400 (48.7%) 수집 중
[댓글] 683/1400 (48.8%) 수집 중
[댓글] 684/1400 (48.9%) 수집 중
[댓글] 685/1400 (48.9%) 수집 중
[댓글] 686/1400 (49.0%) 수집 중
[댓글] 687/1400 (49.1%) 수집 중
[댓글] 688/1400 (49.1%) 수집 중
[댓글] 689/1400 (49.2%) 수집 중
[댓글] 690/1400 (49.3%) 수집 중
[댓글] 691/1400 (49.4%) 수집 중
[댓글] 692/1400 (49.4%) 수집 중
[댓글] 693/1400 (49.5%) 수집 중
[댓글] 694/1400 (49.6%) 수집 중
[댓글] 695/1400 (49.6%) 수집 중
[댓글] 696/1400 (49.7%) 수집 중
[댓글] 697/1400 (49.8%) 수집 중
[댓글] 698/1400 (49.9%) 수집 중
[댓글] 699/1400 (49.9%) 수집 중
[댓글] 700/1400 (50.0%) 수집 중
[댓글] 701/1400 (50.1%) 수집 중
[댓글] 702/1400 (50.1%) 수집 중
[댓글] 703/1400 (50.2%) 수집 중
[댓글] 704/1400 (50.3%) 수집 중
[댓글] 705/1400 (50.4%) 수집 중
[댓글] 706/1400 (50.4%) 수집 중
[댓글] 707/1400 (50.5%) 수집 중
[댓글] 708/1400 (50.6%) 수집 중
[댓글] 709/1400 (50.6%) 수집 중
[댓글] 710/1400 (50.7%) 수집 중
[댓글] 711/1400 (50.8%) 수집 중
[댓글] 712/1400 (50.9%) 수집 중
[댓글] 713/1400 (50.9%) 수집 중
[댓글] 714/1400 (51.0%) 수집 중
[댓글] 715/1400 (51.1%) 수집 중
[댓글] 716/1400 (51.1%) 수집 중
[댓글] 717/1400 (51.2%) 수집 중
[댓글] 718/1400 (51.3%) 수집 중
[댓글] 719/1400 (51.4%) 수집 중
[댓글] 720/1400 (51.4%) 수집 중
[댓글] 721/1400 (51.5%) 수집 중
[댓글] 722/1400 (51.6%) 수집 중
[댓글] 723/1400 (51.6%) 수집 중
[댓글] 724/1400 (51.7%) 수집 중
[댓글] 725/1400 (51.8%) 수집 중
[댓글] 726/1400 (51.9%) 수집 중
[댓글] 727/1400 (51.9%) 수집 중
[댓글] 728/1400 (52.0%) 수집 중

In [14]:
# import
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time
import os

BASE_URL = "https://www.inven.co.kr/board/aion2/6388"
HEADERS = {"User-Agent": "Mozilla/5.0"}

MAX_PAGE = 20
BASE_DIR = "inven_out/aion2"
os.makedirs(BASE_DIR, exist_ok=True)

def get_post_links(page):
    url = f"{BASE_URL}?page={page}"
    res = requests.get(url, headers=HEADERS)
    soup = BeautifulSoup(res.text, "html.parser")

    posts = []
    rows = soup.select("tr")

    for row in rows:
        title_tag = row.select_one("td.tit a.subject-link")
        if not title_tag:
            continue

        posts.append({
            "title": title_tag.text.strip(),
            "url": title_tag["href"]
        })

    return posts

def get_post_detail(post):
    res = requests.get(post["url"], headers=HEADERS)
    soup = BeautifulSoup(res.text, "html.parser")

    # 본문 (comment로 쓸 예정)
    content_tag = soup.select_one(".contentBody")
    content = content_tag.text.strip() if content_tag else ""

    # 작성일
    created_at = ""
    date_tag = soup.select_one(".articleDate")
    if date_tag:
        created_at = date_tag.text.strip()

    # 조회수
    views = 0
    view_tag = soup.select_one(".articleHit")
    if view_tag:
        try:
            views = int(view_tag.text.replace(",", "").strip())
        except:
            pass

    # 좋아요
    likes = 0
    like_tag = soup.select_one("div.recommend span.num")
    if like_tag:
        try:
            likes = int(like_tag.text.strip())
        except:
            pass

    # 댓글
    comments = []
    comment_tags = soup.select(".cmtContent")
    for c in comment_tags:
        txt = c.text.strip()
        if txt:
            comments.append(txt)

    return {
        "title": post["title"],
        "content": content,
        "comments": comments,
        "url": post["url"],
        "created_at": created_at,
        "views": views,
        "likes": likes,
        "comment_count": len(comments)
    }

# 전체 수집
all_posts = []

for page in range(1, MAX_PAGE + 1):
    print(f"[게시글] {page}/{MAX_PAGE} ({round(page/MAX_PAGE*100,1)}%)")

    posts = get_post_links(page)
    if not posts:
        print("게시글 없음 → 종료")
        break

    all_posts.extend(posts)
    time.sleep(1)

print(f"총 게시글 수: {len(all_posts)}")

# 상세 + 댓글 수집
final_data = []
total = len(all_posts)

for idx, post in enumerate(all_posts, 1):
    print(f"[댓글] {idx}/{total} ({round(idx/total*100,1)}%)")

    detail = get_post_detail(post)

    # 본문을 comment로 사용
    if detail["comments"]:
        for c in detail["comments"]:
            final_data.append({
                "title": detail["title"],
                "comment": c,  # 댓글
                "post_content": detail["content"],  # 본문 따로 유지 (추천)
                "url": detail["url"],
                "created_at": detail["created_at"],
                "views": detail["views"],
                "likes": detail["likes"],
                "comment_count": detail["comment_count"]
            })
    else:
        final_data.append({
            "title": detail["title"],
            "comment": "",  
            "post_content": detail["content"],
            "url": detail["url"],
            "created_at": detail["created_at"],
            "views": detail["views"],
            "likes": detail["likes"],
            "comment_count": detail["comment_count"]
        })

    time.sleep(0.5)

# 저장
df = pd.DataFrame(final_data)

today = pd.Timestamp.now().strftime("%Y%m%d")
filename = os.path.join(BASE_DIR, f"aion2_{today}.csv")

df.to_csv(filename, index=False, encoding="utf-8-sig")

print(f"저장 완료: {filename}")

[게시글] 1/20 (5.0%)
[게시글] 2/20 (10.0%)
[게시글] 3/20 (15.0%)
[게시글] 4/20 (20.0%)
[게시글] 5/20 (25.0%)
[게시글] 6/20 (30.0%)
[게시글] 7/20 (35.0%)
[게시글] 8/20 (40.0%)
[게시글] 9/20 (45.0%)
[게시글] 10/20 (50.0%)
[게시글] 11/20 (55.0%)
[게시글] 12/20 (60.0%)
[게시글] 13/20 (65.0%)
[게시글] 14/20 (70.0%)
[게시글] 15/20 (75.0%)
[게시글] 16/20 (80.0%)
[게시글] 17/20 (85.0%)
[게시글] 18/20 (90.0%)
[게시글] 19/20 (95.0%)
[게시글] 20/20 (100.0%)
총 게시글 수: 1400
[댓글] 1/1400 (0.1%)
[댓글] 2/1400 (0.1%)
[댓글] 3/1400 (0.2%)
[댓글] 4/1400 (0.3%)
[댓글] 5/1400 (0.4%)
[댓글] 6/1400 (0.4%)
[댓글] 7/1400 (0.5%)
[댓글] 8/1400 (0.6%)
[댓글] 9/1400 (0.6%)
[댓글] 10/1400 (0.7%)
[댓글] 11/1400 (0.8%)
[댓글] 12/1400 (0.9%)
[댓글] 13/1400 (0.9%)
[댓글] 14/1400 (1.0%)
[댓글] 15/1400 (1.1%)
[댓글] 16/1400 (1.1%)
[댓글] 17/1400 (1.2%)
[댓글] 18/1400 (1.3%)
[댓글] 19/1400 (1.4%)
[댓글] 20/1400 (1.4%)
[댓글] 21/1400 (1.5%)
[댓글] 22/1400 (1.6%)
[댓글] 23/1400 (1.6%)
[댓글] 24/1400 (1.7%)
[댓글] 25/1400 (1.8%)
[댓글] 26/1400 (1.9%)
[댓글] 27/1400 (1.9%)
[댓글] 28/1400 (2.0%)
[댓글] 29/1400 (2.1%)
[댓글] 30/1400 (2.1%)
[댓글] 31/1400 (2.2%)
[댓글] 32/1400 (2.3%)
[댓글] 33/1400 (2.4%)
[댓글] 34/1400 (2.4%)
[댓글] 35/1400 (2.5%)
[댓글] 36/1400 (2.6%)
[댓글] 37/1400 (2.6%)
[댓글] 38/1400 (2.7%)
[댓글] 39/1400 (2.8%)
[댓글] 40/1400 (2.9%)
[댓글] 41/1400 (2.9%)
[댓글] 42/1400 (3.0%)
[댓글] 43/1400 (3.1%)
[댓글] 44/1400 (3.1%)
[댓글] 45/1400 (3.2%)
[댓글] 46/1400 (3.3%)
[댓글] 47/1400 (3.4%)
[댓글] 48/1400 (3.4%)
[댓글] 49/1400 (3.5%)
[댓글] 50/1400 (3.6%)
[댓글] 51/1400 (3.6%)
[댓글] 52/1400 (3.7%)
[댓글] 53/1400 (3.8%)
[댓글] 54/1400 (3.9%)
[댓글] 55/1400 (3.9%)
[댓글] 56/1400 (4.0%)
[댓글] 57/1400 (4.1%)
[댓글] 58/1400 (4.1%)
[댓글] 59/1400 (4.2%)
[댓글] 60/1400 (4.3%)
[댓글] 61/1400 (4.4%)
[댓글] 62/1400 (4.4%)
[댓글] 63/1400 (4.5%)
[댓글] 64/1400 (4.6%)
[댓글] 65/1400 (4.6%)
[댓글] 66/1400 (4.7%)
[댓글] 67/1400 (4.8%)
[댓글] 68/1400 (4.9%)
[댓글] 69/1400 (4.9%)
[댓글] 70/1400 (5.0%)
[댓글] 71/1400 (5.1%)
[댓글] 72/1400 (5.1%)
[댓글] 73/1400 (5.2%)
[댓글] 74/1400 (5.3%)
[댓글] 75/1400 (5.4%)
[댓글] 76/1400 (5.4%)
[댓글] 77/1400 (5.5%)
[댓글] 78/1400 (5.6%)
[댓글] 79/1400 (5.6%)
[댓글] 80/1400 (5.7%)
[댓글] 81/1400 (5.8%)
[댓글] 82/1400 (5.9%)
[댓글] 83/1400 (5.9%)
[댓글] 84/1400 (6.0%)
[댓글] 85/1400 (6.1%)
[댓글] 86/1400 (6.1%)
[댓글] 87/1400 (6.2%)
[댓글] 88/1400 (6.3%)
[댓글] 89/1400 (6.4%)
[댓글] 90/1400 (6.4%)
[댓글] 91/1400 (6.5%)
[댓글] 92/1400 (6.6%)
[댓글] 93/1400 (6.6%)
[댓글] 94/1400 (6.7%)
[댓글] 95/1400 (6.8%)
[댓글] 96/1400 (6.9%)
[댓글] 97/1400 (6.9%)
[댓글] 98/1400 (7.0%)
[댓글] 99/1400 (7.1%)
[댓글] 100/1400 (7.1%)
[댓글] 101/1400 (7.2%)
[댓글] 102/1400 (7.3%)
[댓글] 103/1400 (7.4%)
[댓글] 104/1400 (7.4%)
[댓글] 105/1400 (7.5%)
[댓글] 106/1400 (7.6%)
[댓글] 107/1400 (7.6%)
[댓글] 108/1400 (7.7%)
[댓글] 109/1400 (7.8%)
[댓글] 110/1400 (7.9%)
[댓글] 111/1400 (7.9%)
[댓글] 112/1400 (8.0%)
[댓글] 113/1400 (8.1%)
[댓글] 114/1400 (8.1%)
[댓글] 115/1400 (8.2%)
[댓글] 116/1400 (8.3%)
[댓글] 117/1400 (8.4%)
[댓글] 118/1400 (8.4%)
[댓글] 119/1400 (8.5%)
[댓글] 120/1400 (8.6%)
[댓글] 121/1400 (8.6%)
[댓글] 122/1400 (8.7%)
[댓글] 123/1400 (8.8%)
[댓글] 124/1400 (8.9%)
[댓글] 125/1400 (8.9%)
[댓글] 126/1400 (9.0%)
[댓글] 127/1400 (9.1%)
[댓글] 128/1400 (9.1%)
[댓글] 129/1400 (9.2%)
[댓글] 130/1400 (9.3%)
[댓글] 131/1400 (9.4%)
[댓글] 132/1400 (9.4%)
[댓글] 133/1400 (9.5%)
[댓글] 134/1400 (9.6%)
[댓글] 135/1400 (9.6%)
[댓글] 136/1400 (9.7%)
[댓글] 137/1400 (9.8%)
[댓글] 138/1400 (9.9%)
[댓글] 139/1400 (9.9%)
[댓글] 140/1400 (10.0%)
[댓글] 141/1400 (10.1%)
[댓글] 142/1400 (10.1%)
[댓글] 143/1400 (10.2%)
[댓글] 144/1400 (10.3%)
[댓글] 145/1400 (10.4%)
[댓글] 146/1400 (10.4%)
[댓글] 147/1400 (10.5%)
[댓글] 148/1400 (10.6%)
[댓글] 149/1400 (10.6%)
[댓글] 150/1400 (10.7%)
[댓글] 151/1400 (10.8%)
[댓글] 152/1400 (10.9%)
[댓글] 153/1400 (10.9%)
[댓글] 154/1400 (11.0%)
[댓글] 155/1400 (11.1%)
[댓글] 156/1400 (11.1%)
[댓글] 157/1400 (11.2%)
[댓글] 158/1400 (11.3%)
[댓글] 159/1400 (11.4%)
[댓글] 160/1400 (11.4%)
[댓글] 161/1400 (11.5%)
[댓글] 162/1400 (11.6%)
[댓글] 163/1400 (11.6%)
[댓글] 164/1400 (11.7%)
[댓글] 165/1400 (11.8%)
[댓글] 166/1400 (11.9%)
[댓글] 167/1400 (11.9%)
[댓글] 168/1400 (12.0%)
[댓글] 169/1400 (12.1%)
[댓글] 170/1400 (12.1%)
[댓글] 171/1400 (12.2%)
[댓글] 172/1400 (12.3%)
[댓글] 173/1400 (12.4%)
[댓글] 174/1400 (12.4%)
[댓글] 175/1400 (12.5%)
[댓글] 176/1400 (12.6%)
[댓글] 177/1400 (12.6%)
[댓글] 178/1400 (12.7%)
[댓글] 179/1400 (12.8%)
[댓글] 180/1400 (12.9%)
[댓글] 181/1400 (12.9%)
[댓글] 182/1400 (13.0%)
[댓글] 183/1400 (13.1%)
[댓글] 184/1400 (13.1%)
[댓글] 185/1400 (13.2%)
[댓글] 186/1400 (13.3%)
[댓글] 187/1400 (13.4%)
[댓글] 188/1400 (13.4%)
[댓글] 189/1400 (13.5%)
[댓글] 190/1400 (13.6%)
[댓글] 191/1400 (13.6%)
[댓글] 192/1400 (13.7%)
[댓글] 193/1400 (13.8%)
[댓글] 194/1400 (13.9%)
[댓글] 195/1400 (13.9%)
[댓글] 196/1400 (14.0%)
[댓글] 197/1400 (14.1%)
[댓글] 198/1400 (14.1%)
[댓글] 199/1400 (14.2%)
[댓글] 200/1400 (14.3%)
[댓글] 201/1400 (14.4%)
[댓글] 202/1400 (14.4%)
[댓글] 203/1400 (14.5%)
[댓글] 204/1400 (14.6%)
[댓글] 205/1400 (14.6%)
[댓글] 206/1400 (14.7%)
[댓글] 207/1400 (14.8%)
[댓글] 208/1400 (14.9%)
[댓글] 209/1400 (14.9%)
[댓글] 210/1400 (15.0%)
[댓글] 211/1400 (15.1%)
[댓글] 212/1400 (15.1%)
[댓글] 213/1400 (15.2%)
[댓글] 214/1400 (15.3%)
[댓글] 215/1400 (15.4%)
[댓글] 216/1400 (15.4%)
[댓글] 217/1400 (15.5%)
[댓글] 218/1400 (15.6%)
[댓글] 219/1400 (15.6%)
[댓글] 220/1400 (15.7%)
[댓글] 221/1400 (15.8%)
[댓글] 222/1400 (15.9%)
[댓글] 223/1400 (15.9%)
[댓글] 224/1400 (16.0%)
[댓글] 225/1400 (16.1%)
[댓글] 226/1400 (16.1%)
[댓글] 227/1400 (16.2%)
[댓글] 228/1400 (16.3%)
[댓글] 229/1400 (16.4%)
[댓글] 230/1400 (16.4%)
[댓글] 231/1400 (16.5%)
[댓글] 232/1400 (16.6%)
[댓글] 233/1400 (16.6%)
[댓글] 234/1400 (16.7%)
[댓글] 235/1400 (16.8%)
[댓글] 236/1400 (16.9%)
[댓글] 237/1400 (16.9%)
[댓글] 238/1400 (17.0%)
[댓글] 239/1400 (17.1%)
[댓글] 240/1400 (17.1%)
[댓글] 241/1400 (17.2%)
[댓글] 242/1400 (17.3%)
[댓글] 243/1400 (17.4%)
[댓글] 244/1400 (17.4%)
[댓글] 245/1400 (17.5%)
[댓글] 246/1400 (17.6%)
[댓글] 247/1400 (17.6%)
[댓글] 248/1400 (17.7%)
[댓글] 249/1400 (17.8%)
[댓글] 250/1400 (17.9%)
[댓글] 251/1400 (17.9%)
[댓글] 252/1400 (18.0%)
[댓글] 253/1400 (18.1%)
[댓글] 254/1400 (18.1%)
[댓글] 255/1400 (18.2%)
[댓글] 256/1400 (18.3%)
[댓글] 257/1400 (18.4%)
[댓글] 258/1400 (18.4%)
[댓글] 259/1400 (18.5%)
[댓글] 260/1400 (18.6%)
[댓글] 261/1400 (18.6%)
[댓글] 262/1400 (18.7%)
[댓글] 263/1400 (18.8%)
[댓글] 264/1400 (18.9%)
[댓글] 265/1400 (18.9%)
[댓글] 266/1400 (19.0%)
[댓글] 267/1400 (19.1%)
[댓글] 268/1400 (19.1%)
[댓글] 269/1400 (19.2%)
[댓글] 270/1400 (19.3%)
[댓글] 271/1400 (19.4%)
[댓글] 272/1400 (19.4%)
[댓글] 273/1400 (19.5%)
[댓글] 274/1400 (19.6%)
[댓글] 275/1400 (19.6%)
[댓글] 276/1400 (19.7%)
[댓글] 277/1400 (19.8%)
[댓글] 278/1400 (19.9%)
[댓글] 279/1400 (19.9%)
[댓글] 280/1400 (20.0%)
[댓글] 281/1400 (20.1%)
[댓글] 282/1400 (20.1%)
[댓글] 283/1400 (20.2%)
[댓글] 284/1400 (20.3%)
[댓글] 285/1400 (20.4%)
[댓글] 286/1400 (20.4%)
[댓글] 287/1400 (20.5%)
[댓글] 288/1400 (20.6%)
[댓글] 289/1400 (20.6%)
[댓글] 290/1400 (20.7%)
[댓글] 291/1400 (20.8%)
[댓글] 292/1400 (20.9%)
[댓글] 293/1400 (20.9%)
[댓글] 294/1400 (21.0%)
[댓글] 295/1400 (21.1%)
[댓글] 296/1400 (21.1%)
[댓글] 297/1400 (21.2%)
[댓글] 298/1400 (21.3%)
[댓글] 299/1400 (21.4%)
[댓글] 300/1400 (21.4%)
[댓글] 301/1400 (21.5%)
[댓글] 302/1400 (21.6%)
[댓글] 303/1400 (21.6%)
[댓글] 304/1400 (21.7%)
[댓글] 305/1400 (21.8%)
[댓글] 306/1400 (21.9%)
[댓글] 307/1400 (21.9%)
[댓글] 308/1400 (22.0%)
[댓글] 309/1400 (22.1%)
[댓글] 310/1400 (22.1%)
[댓글] 311/1400 (22.2%)
[댓글] 312/1400 (22.3%)
[댓글] 313/1400 (22.4%)
[댓글] 314/1400 (22.4%)
[댓글] 315/1400 (22.5%)
[댓글] 316/1400 (22.6%)
[댓글] 317/1400 (22.6%)
[댓글] 318/1400 (22.7%)
[댓글] 319/1400 (22.8%)
[댓글] 320/1400 (22.9%)
[댓글] 321/1400 (22.9%)
[댓글] 322/1400 (23.0%)
[댓글] 323/1400 (23.1%)
[댓글] 324/1400 (23.1%)
[댓글] 325/1400 (23.2%)
[댓글] 326/1400 (23.3%)
[댓글] 327/1400 (23.4%)
[댓글] 328/1400 (23.4%)
[댓글] 329/1400 (23.5%)
[댓글] 330/1400 (23.6%)
[댓글] 331/1400 (23.6%)
[댓글] 332/1400 (23.7%)
[댓글] 333/1400 (23.8%)
[댓글] 334/1400 (23.9%)
[댓글] 335/1400 (23.9%)
[댓글] 336/1400 (24.0%)
[댓글] 337/1400 (24.1%)
[댓글] 338/1400 (24.1%)
[댓글] 339/1400 (24.2%)
[댓글] 340/1400 (24.3%)
[댓글] 341/1400 (24.4%)
[댓글] 342/1400 (24.4%)
[댓글] 343/1400 (24.5%)
[댓글] 344/1400 (24.6%)
[댓글] 345/1400 (24.6%)
[댓글] 346/1400 (24.7%)
[댓글] 347/1400 (24.8%)
[댓글] 348/1400 (24.9%)
[댓글] 349/1400 (24.9%)
[댓글] 350/1400 (25.0%)
[댓글] 351/1400 (25.1%)
[댓글] 352/1400 (25.1%)
[댓글] 353/1400 (25.2%)
[댓글] 354/1400 (25.3%)
[댓글] 355/1400 (25.4%)
[댓글] 356/1400 (25.4%)
[댓글] 357/1400 (25.5%)
[댓글] 358/1400 (25.6%)
[댓글] 359/1400 (25.6%)
[댓글] 360/1400 (25.7%)
[댓글] 361/1400 (25.8%)
[댓글] 362/1400 (25.9%)
[댓글] 363/1400 (25.9%)
[댓글] 364/1400 (26.0%)
[댓글] 365/1400 (26.1%)
[댓글] 366/1400 (26.1%)
[댓글] 367/1400 (26.2%)
[댓글] 368/1400 (26.3%)
[댓글] 369/1400 (26.4%)
[댓글] 370/1400 (26.4%)
[댓글] 371/1400 (26.5%)
[댓글] 372/1400 (26.6%)
[댓글] 373/1400 (26.6%)
[댓글] 374/1400 (26.7%)
[댓글] 375/1400 (26.8%)
[댓글] 376/1400 (26.9%)
[댓글] 377/1400 (26.9%)
[댓글] 378/1400 (27.0%)
[댓글] 379/1400 (27.1%)
[댓글] 380/1400 (27.1%)
[댓글] 381/1400 (27.2%)
[댓글] 382/1400 (27.3%)
[댓글] 383/1400 (27.4%)
[댓글] 384/1400 (27.4%)
[댓글] 385/1400 (27.5%)
[댓글] 386/1400 (27.6%)
[댓글] 387/1400 (27.6%)
[댓글] 388/1400 (27.7%)
[댓글] 389/1400 (27.8%)
[댓글] 390/1400 (27.9%)
[댓글] 391/1400 (27.9%)
[댓글] 392/1400 (28.0%)
[댓글] 393/1400 (28.1%)
[댓글] 394/1400 (28.1%)
[댓글] 395/1400 (28.2%)
[댓글] 396/1400 (28.3%)
[댓글] 397/1400 (28.4%)
[댓글] 398/1400 (28.4%)
[댓글] 399/1400 (28.5%)
[댓글] 400/1400 (28.6%)
[댓글] 401/1400 (28.6%)
[댓글] 402/1400 (28.7%)
[댓글] 403/1400 (28.8%)
[댓글] 404/1400 (28.9%)
[댓글] 405/1400 (28.9%)
[댓글] 406/1400 (29.0%)
[댓글] 407/1400 (29.1%)
[댓글] 408/1400 (29.1%)
[댓글] 409/1400 (29.2%)
[댓글] 410/1400 (29.3%)
[댓글] 411/1400 (29.4%)
[댓글] 412/1400 (29.4%)
[댓글] 413/1400 (29.5%)
[댓글] 414/1400 (29.6%)
[댓글] 415/1400 (29.6%)
[댓글] 416/1400 (29.7%)
[댓글] 417/1400 (29.8%)
[댓글] 418/1400 (29.9%)
[댓글] 419/1400 (29.9%)
[댓글] 420/1400 (30.0%)
[댓글] 421/1400 (30.1%)
[댓글] 422/1400 (30.1%)
[댓글] 423/1400 (30.2%)
[댓글] 424/1400 (30.3%)
[댓글] 425/1400 (30.4%)
[댓글] 426/1400 (30.4%)
[댓글] 427/1400 (30.5%)
[댓글] 428/1400 (30.6%)
[댓글] 429/1400 (30.6%)
[댓글] 430/1400 (30.7%)
[댓글] 431/1400 (30.8%)
[댓글] 432/1400 (30.9%)
[댓글] 433/1400 (30.9%)
[댓글] 434/1400 (31.0%)
[댓글] 435/1400 (31.1%)
[댓글] 436/1400 (31.1%)
[댓글] 437/1400 (31.2%)
[댓글] 438/1400 (31.3%)
[댓글] 439/1400 (31.4%)
[댓글] 440/1400 (31.4%)
[댓글] 441/1400 (31.5%)
[댓글] 442/1400 (31.6%)
[댓글] 443/1400 (31.6%)
[댓글] 444/1400 (31.7%)
[댓글] 445/1400 (31.8%)
[댓글] 446/1400 (31.9%)
[댓글] 447/1400 (31.9%)
[댓글] 448/1400 (32.0%)
[댓글] 449/1400 (32.1%)
[댓글] 450/1400 (32.1%)
[댓글] 451/1400 (32.2%)
[댓글] 452/1400 (32.3%)
[댓글] 453/1400 (32.4%)
[댓글] 454/1400 (32.4%)
[댓글] 455/1400 (32.5%)
[댓글] 456/1400 (32.6%)
[댓글] 457/1400 (32.6%)
[댓글] 458/1400 (32.7%)
[댓글] 459/1400 (32.8%)
[댓글] 460/1400 (32.9%)
[댓글] 461/1400 (32.9%)
[댓글] 462/1400 (33.0%)
[댓글] 463/1400 (33.1%)
[댓글] 464/1400 (33.1%)
[댓글] 465/1400 (33.2%)
[댓글] 466/1400 (33.3%)
[댓글] 467/1400 (33.4%)
[댓글] 468/1400 (33.4%)
[댓글] 469/1400 (33.5%)
[댓글] 470/1400 (33.6%)
[댓글] 471/1400 (33.6%)
[댓글] 472/1400 (33.7%)
[댓글] 473/1400 (33.8%)
[댓글] 474/1400 (33.9%)
[댓글] 475/1400 (33.9%)
[댓글] 476/1400 (34.0%)
[댓글] 477/1400 (34.1%)
[댓글] 478/1400 (34.1%)
[댓글] 479/1400 (34.2%)
[댓글] 480/1400 (34.3%)
[댓글] 481/1400 (34.4%)
[댓글] 482/1400 (34.4%)
[댓글] 483/1400 (34.5%)
[댓글] 484/1400 (34.6%)
[댓글] 485/1400 (34.6%)
[댓글] 486/1400 (34.7%)
[댓글] 487/1400 (34.8%)
[댓글] 488/1400 (34.9%)
[댓글] 489/1400 (34.9%)
[댓글] 490/1400 (35.0%)
[댓글] 491/1400 (35.1%)
[댓글] 492/1400 (35.1%)
[댓글] 493/1400 (35.2%)
[댓글] 494/1400 (35.3%)
[댓글] 495/1400 (35.4%)
[댓글] 496/1400 (35.4%)
[댓글] 497/1400 (35.5%)
[댓글] 498/1400 (35.6%)
[댓글] 499/1400 (35.6%)
[댓글] 500/1400 (35.7%)
[댓글] 501/1400 (35.8%)
[댓글] 502/1400 (35.9%)
[댓글] 503/1400 (35.9%)
[댓글] 504/1400 (36.0%)
[댓글] 505/1400 (36.1%)
[댓글] 506/1400 (36.1%)
[댓글] 507/1400 (36.2%)
[댓글] 508/1400 (36.3%)
[댓글] 509/1400 (36.4%)
[댓글] 510/1400 (36.4%)
[댓글] 511/1400 (36.5%)
[댓글] 512/1400 (36.6%)
[댓글] 513/1400 (36.6%)
[댓글] 514/1400 (36.7%)
[댓글] 515/1400 (36.8%)
[댓글] 516/1400 (36.9%)
[댓글] 517/1400 (36.9%)
[댓글] 518/1400 (37.0%)
[댓글] 519/1400 (37.1%)
[댓글] 520/1400 (37.1%)
[댓글] 521/1400 (37.2%)
[댓글] 522/1400 (37.3%)
[댓글] 523/1400 (37.4%)
[댓글] 524/1400 (37.4%)
[댓글] 525/1400 (37.5%)
[댓글] 526/1400 (37.6%)
[댓글] 527/1400 (37.6%)
[댓글] 528/1400 (37.7%)
[댓글] 529/1400 (37.8%)
[댓글] 530/1400 (37.9%)
[댓글] 531/1400 (37.9%)
[댓글] 532/1400 (38.0%)
[댓글] 533/1400 (38.1%)
[댓글] 534/1400 (38.1%)
[댓글] 535/1400 (38.2%)
[댓글] 536/1400 (38.3%)
[댓글] 537/1400 (38.4%)
[댓글] 538/1400 (38.4%)
[댓글] 539/1400 (38.5%)
[댓글] 540/1400 (38.6%)
[댓글] 541/1400 (38.6%)
[댓글] 542/1400 (38.7%)
[댓글] 543/1400 (38.8%)
[댓글] 544/1400 (38.9%)
[댓글] 545/1400 (38.9%)
[댓글] 546/1400 (39.0%)
[댓글] 547/1400 (39.1%)
[댓글] 548/1400 (39.1%)
[댓글] 549/1400 (39.2%)
[댓글] 550/1400 (39.3%)
[댓글] 551/1400 (39.4%)
[댓글] 552/1400 (39.4%)
[댓글] 553/1400 (39.5%)
[댓글] 554/1400 (39.6%)
[댓글] 555/1400 (39.6%)
[댓글] 556/1400 (39.7%)
[댓글] 557/1400 (39.8%)
[댓글] 558/1400 (39.9%)
[댓글] 559/1400 (39.9%)
[댓글] 560/1400 (40.0%)
[댓글] 561/1400 (40.1%)
[댓글] 562/1400 (40.1%)
[댓글] 563/1400 (40.2%)
[댓글] 564/1400 (40.3%)
[댓글] 565/1400 (40.4%)
[댓글] 566/1400 (40.4%)
[댓글] 567/1400 (40.5%)
[댓글] 568/1400 (40.6%)
[댓글] 569/1400 (40.6%)
[댓글] 570/1400 (40.7%)
[댓글] 571/1400 (40.8%)
[댓글] 572/1400 (40.9%)
[댓글] 573/1400 (40.9%)
[댓글] 574/1400 (41.0%)
[댓글] 575/1400 (41.1%)
[댓글] 576/1400 (41.1%)
[댓글] 577/1400 (41.2%)
[댓글] 578/1400 (41.3%)
[댓글] 579/1400 (41.4%)
[댓글] 580/1400 (41.4%)
[댓글] 581/1400 (41.5%)
[댓글] 582/1400 (41.6%)
[댓글] 583/1400 (41.6%)
[댓글] 584/1400 (41.7%)
[댓글] 585/1400 (41.8%)
[댓글] 586/1400 (41.9%)
[댓글] 587/1400 (41.9%)
[댓글] 588/1400 (42.0%)
[댓글] 589/1400 (42.1%)
[댓글] 590/1400 (42.1%)
[댓글] 591/1400 (42.2%)
[댓글] 592/1400 (42.3%)
[댓글] 593/1400 (42.4%)
[댓글] 594/1400 (42.4%)
[댓글] 595/1400 (42.5%)
[댓글] 596/1400 (42.6%)
[댓글] 597/1400 (42.6%)
[댓글] 598/1400 (42.7%)
[댓글] 599/1400 (42.8%)
[댓글] 600/1400 (42.9%)
[댓글] 601/1400 (42.9%)
[댓글] 602/1400 (43.0%)
[댓글] 603/1400 (43.1%)
[댓글] 604/1400 (43.1%)
[댓글] 605/1400 (43.2%)
[댓글] 606/1400 (43.3%)
[댓글] 607/1400 (43.4%)
[댓글] 608/1400 (43.4%)
[댓글] 609/1400 (43.5%)
[댓글] 610/1400 (43.6%)
[댓글] 611/1400 (43.6%)
[댓글] 612/1400 (43.7%)
[댓글] 613/1400 (43.8%)
[댓글] 614/1400 (43.9%)
[댓글] 615/1400 (43.9%)
[댓글] 616/1400 (44.0%)
[댓글] 617/1400 (44.1%)
[댓글] 618/1400 (44.1%)
[댓글] 619/1400 (44.2%)
[댓글] 620/1400 (44.3%)
[댓글] 621/1400 (44.4%)
[댓글] 622/1400 (44.4%)
[댓글] 623/1400 (44.5%)
[댓글] 624/1400 (44.6%)
[댓글] 625/1400 (44.6%)
[댓글] 626/1400 (44.7%)
[댓글] 627/1400 (44.8%)
[댓글] 628/1400 (44.9%)
[댓글] 629/1400 (44.9%)
[댓글] 630/1400 (45.0%)
[댓글] 631/1400 (45.1%)
[댓글] 632/1400 (45.1%)
[댓글] 633/1400 (45.2%)
[댓글] 634/1400 (45.3%)
[댓글] 635/1400 (45.4%)
[댓글] 636/1400 (45.4%)
[댓글] 637/1400 (45.5%)
[댓글] 638/1400 (45.6%)
[댓글] 639/1400 (45.6%)
[댓글] 640/1400 (45.7%)
[댓글] 641/1400 (45.8%)
[댓글] 642/1400 (45.9%)
[댓글] 643/1400 (45.9%)
[댓글] 644/1400 (46.0%)
[댓글] 645/1400 (46.1%)
[댓글] 646/1400 (46.1%)
[댓글] 647/1400 (46.2%)
[댓글] 648/1400 (46.3%)
[댓글] 649/1400 (46.4%)
[댓글] 650/1400 (46.4%)
[댓글] 651/1400 (46.5%)
[댓글] 652/1400 (46.6%)
[댓글] 653/1400 (46.6%)
[댓글] 654/1400 (46.7%)
[댓글] 655/1400 (46.8%)
[댓글] 656/1400 (46.9%)
[댓글] 657/1400 (46.9%)
[댓글] 658/1400 (47.0%)
[댓글] 659/1400 (47.1%)
[댓글] 660/1400 (47.1%)
[댓글] 661/1400 (47.2%)
[댓글] 662/1400 (47.3%)
[댓글] 663/1400 (47.4%)
[댓글] 664/1400 (47.4%)
[댓글] 665/1400 (47.5%)
[댓글] 666/1400 (47.6%)
[댓글] 667/1400 (47.6%)
[댓글] 668/1400 (47.7%)
[댓글] 669/1400 (47.8%)
[댓글] 670/1400 (47.9%)
[댓글] 671/1400 (47.9%)
[댓글] 672/1400 (48.0%)
[댓글] 673/1400 (48.1%)
[댓글] 674/1400 (48.1%)
[댓글] 675/1400 (48.2%)
[댓글] 676/1400 (48.3%)
[댓글] 677/1400 (48.4%)
[댓글] 678/1400 (48.4%)
[댓글] 679/1400 (48.5%)
[댓글] 680/1400 (48.6%)
[댓글] 681/1400 (48.6%)
[댓글] 682/1400 (48.7%)
[댓글] 683/1400 (48.8%)
[댓글] 684/1400 (48.9%)
[댓글] 685/1400 (48.9%)
[댓글] 686/1400 (49.0%)
[댓글] 687/1400 (49.1%)
[댓글] 688/1400 (49.1%)
[댓글] 689/1400 (49.2%)
[댓글] 690/1400 (49.3%)
[댓글] 691/1400 (49.4%)
[댓글] 692/1400 (49.4%)
[댓글] 693/1400 (49.5%)
[댓글] 694/1400 (49.6%)
[댓글] 695/1400 (49.6%)
[댓글] 696/1400 (49.7%)
[댓글] 697/1400 (49.8%)
[댓글] 698/1400 (49.9%)
[댓글] 699/1400 (49.9%)
[댓글] 700/1400 (50.0%)
[댓글] 701/1400 (50.1%)
[댓글] 702/1400 (50.1%)
[댓글] 703/1400 (50.2%)
[댓글] 704/1400 (50.3%)
[댓글] 705/1400 (50.4%)
[댓글] 706/1400 (50.4%)
[댓글] 707/1400 (50.5%)
[댓글] 708/1400 (50.6%)
[댓글] 709/1400 (50.6%)
[댓글] 710/1400 (50.7%)
[댓글] 711/1400 (50.8%)
[댓글] 712/1400 (50.9%)
[댓글] 713/1400 (50.9%)
[댓글] 714/1400 (51.0%)
[댓글] 715/1400 (51.1%)
[댓글] 716/1400 (51.1%)
[댓글] 717/1400 (51.2%)
[댓글] 718/1400 (51.3%)
[댓글] 719/1400 (51.4%)
[댓글] 720/1400 (51.4%)
[댓글] 721/1400 (51.5%)
[댓글] 722/1400 (51.6%)
[댓글] 723/1400 (51.6%)
[댓글] 724/1400 (51.7%)
[댓글] 725/1400 (51.8%)
[댓글] 726/1400 (51.9%)
[댓글] 727/1400 (51.9%)
[댓글] 728/1400 (52.0%)
[댓글] 729/1400 (52.1%)
[댓글] 730/1400 (52.1%)
[댓글] 731/1400 (52.2%)
[댓글] 732/1400 (52.3%)
[댓글] 733/1400 (52.4%)
[댓글] 734/1400 (52.4%)
[댓글] 735/1400 (52.5%)
[댓글] 736/1400 (52.6%)
[댓글] 737/1400 (52.6%)
[댓글] 738/1400 (52.7%)
[댓글] 739/1400 (52.8%)
[댓글] 740/1400 (52.9%)
[댓글] 741/1400 (52.9%)
[댓글] 742/1400 (53.0%)
[댓글] 743/1400 (53.1%)
[댓글] 744/1400 (53.1%)
[댓글] 745/1400 (53.2%)
[댓글] 746/1400 (53.3%)
[댓글] 747/1400 (53.4%)
[댓글] 748/1400 (53.4%)
[댓글] 749/1400 (53.5%)
[댓글] 750/1400 (53.6%)
[댓글] 751/1400 (53.6%)
[댓글] 752/1400 (53.7%)
[댓글] 753/1400 (53.8%)
[댓글] 754/1400 (53.9%)
[댓글] 755/1400 (53.9%)
[댓글] 756/1400 (54.0%)
[댓글] 757/1400 (54.1%)
[댓글] 758/1400 (54.1%)
[댓글] 759/1400 (54.2%)
[댓글] 760/1400 (54.3%)
[댓글] 761/1400 (54.4%)
[댓글] 762/1400 (54.4%)
[댓글] 763/1400 (54.5%)
[댓글] 764/1400 (54.6%)
[댓글] 765/1400 (54.6%)
[댓글] 766/1400 (54.7%)
[댓글] 767/1400 (54.8%)
[댓글] 768/1400 (54.9%)
[댓글] 769/1400 (54.9%)
[댓글] 770/1400 (55.0%)
[댓글] 771/1400 (55.1%)
[댓글] 772/1400 (55.1%)
[댓글] 773/1400 (55.2%)
[댓글] 774/1400 (55.3%)
[댓글] 775/1400 (55.4%)
[댓글] 776/1400 (55.4%)
[댓글] 777/1400 (55.5%)
[댓글] 778/1400 (55.6%)
[댓글] 779/1400 (55.6%)
[댓글] 780/1400 (55.7%)
[댓글] 781/1400 (55.8%)
[댓글] 782/1400 (55.9%)
[댓글] 783/1400 (55.9%)
[댓글] 784/1400 (56.0%)
[댓글] 785/1400 (56.1%)
[댓글] 786/1400 (56.1%)
[댓글] 787/1400 (56.2%)
[댓글] 788/1400 (56.3%)
[댓글] 789/1400 (56.4%)
[댓글] 790/1400 (56.4%)
[댓글] 791/1400 (56.5%)
[댓글] 792/1400 (56.6%)
[댓글] 793/1400 (56.6%)
[댓글] 794/1400 (56.7%)
[댓글] 795/1400 (56.8%)
[댓글] 796/1400 (56.9%)
[댓글] 797/1400 (56.9%)
[댓글] 798/1400 (57.0%)
[댓글] 799/1400 (57.1%)
[댓글] 800/1400 (57.1%)
[댓글] 801/1400 (57.2%)
[댓글] 802/1400 (57.3%)
[댓글] 803/1400 (57.4%)
[댓글] 804/1400 (57.4%)
[댓글] 805/1400 (57.5%)
[댓글] 806/1400 (57.6%)
[댓글] 807/1400 (57.6%)
[댓글] 808/1400 (57.7%)
[댓글] 809/1400 (57.8%)
[댓글] 810/1400 (57.9%)
[댓글] 811/1400 (57.9%)
[댓글] 812/1400 (58.0%)
[댓글] 813/1400 (58.1%)
[댓글] 814/1400 (58.1%)
[댓글] 815/1400 (58.2%)
[댓글] 816/1400 (58.3%)
[댓글] 817/1400 (58.4%)
[댓글] 818/1400 (58.4%)
[댓글] 819/1400 (58.5%)
[댓글] 820/1400 (58.6%)
[댓글] 821/1400 (58.6%)
[댓글] 822/1400 (58.7%)
[댓글] 823/1400 (58.8%)
[댓글] 824/1400 (58.9%)
[댓글] 825/1400 (58.9%)
[댓글] 826/1400 (59.0%)
[댓글] 827/1400 (59.1%)
[댓글] 828/1400 (59.1%)
[댓글] 829/1400 (59.2%)
[댓글] 830/1400 (59.3%)
[댓글] 831/1400 (59.4%)
[댓글] 832/1400 (59.4%)
[댓글] 833/1400 (59.5%)
[댓글] 834/1400 (59.6%)
[댓글] 835/1400 (59.6%)
[댓글] 836/1400 (59.7%)
[댓글] 837/1400 (59.8%)
[댓글] 838/1400 (59.9%)
[댓글] 839/1400 (59.9%)
[댓글] 840/1400 (60.0%)
[댓글] 841/1400 (60.1%)
[댓글] 842/1400 (60.1%)
[댓글] 843/1400 (60.2%)
[댓글] 844/1400 (60.3%)
[댓글] 845/1400 (60.4%)
[댓글] 846/1400 (60.4%)
[댓글] 847/1400 (60.5%)
[댓글] 848/1400 (60.6%)
[댓글] 849/1400 (60.6%)
[댓글] 850/1400 (60.7%)
[댓글] 851/1400 (60.8%)
[댓글] 852/1400 (60.9%)
[댓글] 853/1400 (60.9%)
[댓글] 854/1400 (61.0%)
[댓글] 855/1400 (61.1%)
[댓글] 856/1400 (61.1%)
[댓글] 857/1400 (61.2%)
[댓글] 858/1400 (61.3%)
[댓글] 859/1400 (61.4%)
[댓글] 860/1400 (61.4%)
[댓글] 861/1400 (61.5%)
[댓글] 862/1400 (61.6%)
[댓글] 863/1400 (61.6%)
[댓글] 864/1400 (61.7%)
[댓글] 865/1400 (61.8%)
[댓글] 866/1400 (61.9%)
[댓글] 867/1400 (61.9%)
[댓글] 868/1400 (62.0%)
[댓글] 869/1400 (62.1%)
[댓글] 870/1400 (62.1%)
[댓글] 871/1400 (62.2%)
[댓글] 872/1400 (62.3%)
[댓글] 873/1400 (62.4%)
[댓글] 874/1400 (62.4%)
[댓글] 875/1400 (62.5%)
[댓글] 876/1400 (62.6%)
[댓글] 877/1400 (62.6%)
[댓글] 878/1400 (62.7%)
[댓글] 879/1400 (62.8%)
[댓글] 880/1400 (62.9%)
[댓글] 881/1400 (62.9%)
[댓글] 882/1400 (63.0%)
[댓글] 883/1400 (63.1%)
[댓글] 884/1400 (63.1%)
[댓글] 885/1400 (63.2%)
[댓글] 886/1400 (63.3%)
[댓글] 887/1400 (63.4%)
[댓글] 888/1400 (63.4%)
[댓글] 889/1400 (63.5%)
[댓글] 890/1400 (63.6%)
[댓글] 891/1400 (63.6%)
[댓글] 892/1400 (63.7%)
[댓글] 893/1400 (63.8%)
[댓글] 894/1400 (63.9%)
[댓글] 895/1400 (63.9%)
[댓글] 896/1400 (64.0%)
[댓글] 897/1400 (64.1%)
[댓글] 898/1400 (64.1%)
[댓글] 899/1400 (64.2%)
[댓글] 900/1400 (64.3%)
[댓글] 901/1400 (64.4%)

In [23]:
# 기존 댓글 컬럼 삭제 (있을 경우만)
cols_to_drop = [col for col in ["comment", "comment_count"] if col in aion_df.columns]
aion_df = aion_df.drop(columns=cols_to_drop)

In [32]:
# content → comment로 이름 변경
aion_df = aion_df.rename(columns={"comment": "content"})

In [33]:
aion_df

,title,content,url,created_at,views,likes
0,[잡담]\n아이온2 인장 캐릭터 인증 가이드,아이온2 인벤에 아이온2 인장 연동 기능이 추가되었습니다. 아래 안내를 따라와 주시...,https://www.inven.co.kr/board/aion2/6388/72656,2026-01-21 12:19,0,0
1,[소식]\n ...,쿠폰 입력 기간 변경 [바로가기]시즌2 일정 변경에 따라 AION2 웰컴백 쿠폰 &...,https://www.inven.co.kr/board/aion2/6388/104900,2026-02-23 19:31,0,0
2,"[잡담]\n전투력 업데이트 완료! 인장 갱신하면 3,000 이니 드려요!","안녕하세요, 아이온2 인벤팀입니다.아이온2 인증 인장에 전투력 수치가 추가되었습니다...",https://www.inven.co.kr/board/aion2/6388/125736,2026-03-19 17:08,0,0
3,[소식]\n ...,[콘텐츠 및 시스템]어비스 매칭 개편어비스 매칭에서 동일 종족도 적대 종족으로 매칭...,https://www.inven.co.kr/board/aion2/6388/131176,2026-03-25 10:23,0,0
4,[소식]\n ...,"두 개의 하늘, 하나의 영광안녕하세요, 데바 여러분. AION2입니다.​항상 AIO...",https://www.inven.co.kr/board/aion2/6388/131177,2026-03-25 10:24,0,0
...,...,...,...,...,...,...
1395,[잡담]\n ...,임점후 수호성 마도 정령성 너프 검성 전체스킬 딜상향 줌 <<<<<<<<<<<수호성...,https://www.inven.co.kr/board/aion2/6388/134053,2026-03-26 13:09,0,0
1396,[잡담]\n ...,얼릉 팔어,https://www.inven.co.kr/board/aion2/6388/134052,2026-03-26 13:09,0,0
1397,[잡담]\n ...,pc로 한다고 pc게임이겠냐호박에 줄긋는다고 수박되냐고 ㅋㅋㅋ직업간 밸런스에서 정통...,https://www.inven.co.kr/board/aion2/6388/134051,2026-03-26 13:09,0,0
1398,[잡담]\n ...,그냥 갑자기 든 생각수호성은 딴딴한 이미지검성은 딜탱 하이브리드 스위치 온오프 만능...,https://www.inven.co.kr/board/aion2/6388/134050,2026-03-26 13:09,0,0
1399,[잡담]\n ...,라방에서 징징 해줘 도배하는 늙은이색히들90프로는 인벤에 있는듯 ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ...,https://www.inven.co.kr/board/aion2/6388/134049,2026-03-26 13:08,0,0

In [35]:
# 한 파일로 합치기

# 파일 경로
aion_path = "inven_out/aion2/aion2_20260326.csv"
lostark_path = "inven_out/lostark_mobile/lostark_mobile_20260325.csv"

# 불러오기
aion_df = pd.read_csv(aion_path)
lostark_df = pd.read_csv(lostark_path)

# 컬럼 추가
aion_df["source"] = "inven_aion2"
lostark_df["source"] = "inven_lostarkmobile"

# 공통 region
aion_df["region"] = "국내"
lostark_df["region"] = "국내"

# 컬럼 구조 맞추기 (혹시 컬럼 다를 경우 대비)
common_cols = list(set(aion_df.columns) | set(lostark_df.columns))

aion_df = aion_df.reindex(columns=common_cols)
lostark_df = lostark_df.reindex(columns=common_cols)

# 합치기
merged_df = pd.concat([aion_df, lostark_df], ignore_index=True)

print("합치기 완료")
print("총 데이터 수:", len(merged_df))
print("컬럼:", merged_df.columns.tolist())

합치기 완료
총 데이터 수: 1625
컬럼: ['region', 'views', 'title', 'created_at', 'content', 'source', 'comment_count', 'likes', 'comment', 'url']

In [36]:
merged_df

,region,views,title,created_at,content,source,comment_count,likes,comment,url
0,국내,0,[잡담]\n아이온2 인장 캐릭터 인증 가이드,2026-01-21 12:19,아이온2 인벤에 아이온2 인장 연동 기능이 추가되었습니다. 아래 안내를 따라와 주시...,inven_aion2,NaN,0,NaN,https://www.inven.co.kr/board/aion2/6388/72656
1,국내,0,[소식]\n ...,2026-02-23 19:31,쿠폰 입력 기간 변경 [바로가기]시즌2 일정 변경에 따라 AION2 웰컴백 쿠폰 &...,inven_aion2,NaN,0,NaN,https://www.inven.co.kr/board/aion2/6388/104900
2,국내,0,"[잡담]\n전투력 업데이트 완료! 인장 갱신하면 3,000 이니 드려요!",2026-03-19 17:08,"안녕하세요, 아이온2 인벤팀입니다.아이온2 인증 인장에 전투력 수치가 추가되었습니다...",inven_aion2,NaN,0,NaN,https://www.inven.co.kr/board/aion2/6388/125736
3,국내,0,[소식]\n ...,2026-03-25 10:23,[콘텐츠 및 시스템]어비스 매칭 개편어비스 매칭에서 동일 종족도 적대 종족으로 매칭...,inven_aion2,NaN,0,NaN,https://www.inven.co.kr/board/aion2/6388/131176
4,국내,0,[소식]\n ...,2026-03-25 10:24,"두 개의 하늘, 하나의 영광안녕하세요, 데바 여러분. AION2입니다.​항상 AIO...",inven_aion2,NaN,0,NaN,https://www.inven.co.kr/board/aion2/6388/131177
...,...,...,...,...,...,...,...,...,...,...
1620,국내,0,[잡담]\n ...,2025-11-14 16:47,소환사 제대로 나와서 즐길수 있었으면 좋겠어요,inven_lostarkmobile,0.0,0,NaN,https://www.inven.co.kr/board/lostarkmobile/63...
1621,국내,0,[잡담]\n ...,2025-11-14 16:42,맞으며,inven_lostarkmobile,0.0,0,NaN,https://www.inven.co.kr/board/lostarkmobile/63...
1622,국내,0,[잡담]\n ...,2025-11-14 15:55,일단 나,inven_lostarkmobile,0.0,0,NaN,https://www.inven.co.kr/board/lostarkmobile/63...
1623,국내,0,[잡담]\n ...,2025-11-14 15:43,기대중입니다,inven_lostarkmobile,0.0,0,NaN,https://www.inven.co.kr/board/lostarkmobile/63...
1624,국내,0,[잡담]\n ...,2025-11-14 15:32,https://youtu.be/2eCOCjKX2fk근데 이거 깨느라 배탬이 모자릅니다,inven_lostarkmobile,0.0,0,NaN,https://www.inven.co.kr/board/lostarkmobile/63...

In [38]:
import re

def contains_link(text: str) -> bool:
    if pd.isna(text):
        return False
    return bool(re.search(r"http[s]?://\S+", str(text)))

# 링크가 있는 행 삭제
merged_df = merged_df[~(merged_df["title"].apply(contains_link) | merged_df["content"].apply(contains_link))].copy()

In [39]:
merged_df

,region,views,title,created_at,content,source,comment_count,likes,comment,url
0,국내,0,[잡담]\n아이온2 인장 캐릭터 인증 가이드,2026-01-21 12:19,아이온2 인벤에 아이온2 인장 연동 기능이 추가되었습니다. 아래 안내를 따라와 주시...,inven_aion2,NaN,0,NaN,https://www.inven.co.kr/board/aion2/6388/72656
1,국내,0,[소식]\n ...,2026-02-23 19:31,쿠폰 입력 기간 변경 [바로가기]시즌2 일정 변경에 따라 AION2 웰컴백 쿠폰 &...,inven_aion2,NaN,0,NaN,https://www.inven.co.kr/board/aion2/6388/104900
2,국내,0,"[잡담]\n전투력 업데이트 완료! 인장 갱신하면 3,000 이니 드려요!",2026-03-19 17:08,"안녕하세요, 아이온2 인벤팀입니다.아이온2 인증 인장에 전투력 수치가 추가되었습니다...",inven_aion2,NaN,0,NaN,https://www.inven.co.kr/board/aion2/6388/125736
3,국내,0,[소식]\n ...,2026-03-25 10:23,[콘텐츠 및 시스템]어비스 매칭 개편어비스 매칭에서 동일 종족도 적대 종족으로 매칭...,inven_aion2,NaN,0,NaN,https://www.inven.co.kr/board/aion2/6388/131176
4,국내,0,[소식]\n ...,2026-03-25 10:24,"두 개의 하늘, 하나의 영광안녕하세요, 데바 여러분. AION2입니다.​항상 AIO...",inven_aion2,NaN,0,NaN,https://www.inven.co.kr/board/aion2/6388/131177
...,...,...,...,...,...,...,...,...,...,...
1619,국내,0,[잡담]\n ...,2025-11-14 16:49,넘 기대됩니다,inven_lostarkmobile,0.0,0,NaN,https://www.inven.co.kr/board/lostarkmobile/63...
1620,국내,0,[잡담]\n ...,2025-11-14 16:47,소환사 제대로 나와서 즐길수 있었으면 좋겠어요,inven_lostarkmobile,0.0,0,NaN,https://www.inven.co.kr/board/lostarkmobile/63...
1621,국내,0,[잡담]\n ...,2025-11-14 16:42,맞으며,inven_lostarkmobile,0.0,0,NaN,https://www.inven.co.kr/board/lostarkmobile/63...
1622,국내,0,[잡담]\n ...,2025-11-14 15:55,일단 나,inven_lostarkmobile,0.0,0,NaN,https://www.inven.co.kr/board/lostarkmobile/63...
1623,국내,0,[잡담]\n ...,2025-11-14 15:43,기대중입니다,inven_lostarkmobile,0.0,0,NaN,https://www.inven.co.kr/board/lostarkmobile/63...

In [41]:
merged_df = merged_df.rename(columns={"content": "selftext"})

In [46]:
merged_df

,region,views,title,created_at,selftext,source,comment_count,likes,comment,url
0,국내,0,[잡담]\n아이온2 인장 캐릭터 인증 가이드,2026-01-21 12:19,아이온2 인벤에 아이온2 인장 연동 기능이 추가되었습니다. 아래 안내를 따라와 주시...,inven_aion2,NaN,0,NaN,https://www.inven.co.kr/board/aion2/6388/72656
1,국내,0,[소식]\n ...,2026-02-23 19:31,쿠폰 입력 기간 변경 [바로가기]시즌2 일정 변경에 따라 AION2 웰컴백 쿠폰 &...,inven_aion2,NaN,0,NaN,https://www.inven.co.kr/board/aion2/6388/104900
2,국내,0,"[잡담]\n전투력 업데이트 완료! 인장 갱신하면 3,000 이니 드려요!",2026-03-19 17:08,"안녕하세요, 아이온2 인벤팀입니다.아이온2 인증 인장에 전투력 수치가 추가되었습니다...",inven_aion2,NaN,0,NaN,https://www.inven.co.kr/board/aion2/6388/125736
3,국내,0,[소식]\n ...,2026-03-25 10:23,[콘텐츠 및 시스템]어비스 매칭 개편어비스 매칭에서 동일 종족도 적대 종족으로 매칭...,inven_aion2,NaN,0,NaN,https://www.inven.co.kr/board/aion2/6388/131176
4,국내,0,[소식]\n ...,2026-03-25 10:24,"두 개의 하늘, 하나의 영광안녕하세요, 데바 여러분. AION2입니다.​항상 AIO...",inven_aion2,NaN,0,NaN,https://www.inven.co.kr/board/aion2/6388/131177
...,...,...,...,...,...,...,...,...,...,...
1619,국내,0,[잡담]\n ...,2025-11-14 16:49,넘 기대됩니다,inven_lostarkmobile,0.0,0,NaN,https://www.inven.co.kr/board/lostarkmobile/63...
1620,국내,0,[잡담]\n ...,2025-11-14 16:47,소환사 제대로 나와서 즐길수 있었으면 좋겠어요,inven_lostarkmobile,0.0,0,NaN,https://www.inven.co.kr/board/lostarkmobile/63...
1621,국내,0,[잡담]\n ...,2025-11-14 16:42,맞으며,inven_lostarkmobile,0.0,0,NaN,https://www.inven.co.kr/board/lostarkmobile/63...
1622,국내,0,[잡담]\n ...,2025-11-14 15:55,일단 나,inven_lostarkmobile,0.0,0,NaN,https://www.inven.co.kr/board/lostarkmobile/63...
1623,국내,0,[잡담]\n ...,2025-11-14 15:43,기대중입니다,inven_lostarkmobile,0.0,0,NaN,https://www.inven.co.kr/board/lostarkmobile/63...

In [50]:
# 아이온2 - [잡담] 포함된 데이터만 필터링
aion_filtered = merged_df[
    (merged_df["source"] == "inven_aion2") &
    (merged_df["title"].str.contains(r"\[잡담\]", na=False))
]

# 로스트아크모바일 그대로 유지
lostark_df = merged_df[merged_df["source"] == "inven_lostarkmobile"]

# 다시 합치기
final_df = pd.concat([aion_filtered, lostark_df], ignore_index=True)
final_df

,region,views,title,created_at,selftext,source,comment_count,likes,comment,url
0,국내,0,[잡담]\n아이온2 인장 캐릭터 인증 가이드,2026-01-21 12:19,아이온2 인벤에 아이온2 인장 연동 기능이 추가되었습니다. 아래 안내를 따라와 주시...,inven_aion2,NaN,0,NaN,https://www.inven.co.kr/board/aion2/6388/72656
1,국내,0,"[잡담]\n전투력 업데이트 완료! 인장 갱신하면 3,000 이니 드려요!",2026-03-19 17:08,"안녕하세요, 아이온2 인벤팀입니다.아이온2 인증 인장에 전투력 수치가 추가되었습니다...",inven_aion2,NaN,0,NaN,https://www.inven.co.kr/board/aion2/6388/125736
2,국내,0,[잡담]\n ...,2026-03-26 13:30,우쮸쮸 끝판왕이네 ㅋㅋ죽는거무섭다니까무한부활줘버리네부활석은 쓰냐?치유들이 잘도 좋아...,inven_aion2,NaN,0,NaN,https://www.inven.co.kr/board/aion2/6388/134112
3,국내,0,[잡담]\n ...,2026-03-26 13:30,일주일도 안돼서 애가 저렇게 타락함?,inven_aion2,NaN,0,NaN,https://www.inven.co.kr/board/aion2/6388/134111
4,국내,0,[잡담]\n ...,2026-03-26 13:29,궁성 탱인데 딜좀 너프해야되는거아님??피흡으로 다버티는데 아이온2는 원거리탱이라는 ...,inven_aion2,NaN,0,NaN,https://www.inven.co.kr/board/aion2/6388/134110
...,...,...,...,...,...,...,...,...,...,...
1497,국내,0,[잡담]\n ...,2025-11-14 16:49,넘 기대됩니다,inven_lostarkmobile,0.0,0,NaN,https://www.inven.co.kr/board/lostarkmobile/63...
1498,국내,0,[잡담]\n ...,2025-11-14 16:47,소환사 제대로 나와서 즐길수 있었으면 좋겠어요,inven_lostarkmobile,0.0,0,NaN,https://www.inven.co.kr/board/lostarkmobile/63...
1499,국내,0,[잡담]\n ...,2025-11-14 16:42,맞으며,inven_lostarkmobile,0.0,0,NaN,https://www.inven.co.kr/board/lostarkmobile/63...
1500,국내,0,[잡담]\n ...,2025-11-14 15:55,일단 나,inven_lostarkmobile,0.0,0,NaN,https://www.inven.co.kr/board/lostarkmobile/63...
1501,국내,0,[잡담]\n ...,2025-11-14 15:43,기대중입니다,inven_lostarkmobile,0.0,0,NaN,https://www.inven.co.kr/board/lostarkmobile/63...

In [51]:
# 저장
final_df.to_csv("inven_all_posts.csv", index=False, encoding="utf-8-sig")